osmandapp/OsmAnd-iOS

Resources/en.lproj/Localizable.strings
Sources/Controllers/OARootViewController.m

Lots of apps seem to implement their own shortcuts which creates confusion for the end-user. Zooming on an Apple Mac or iOS app has always used `CMD +` and `CMD -`. Resetting the zoom level normally is `CMD 0`.
So to be more in line with Apple's default shortcuts from apps like Apple Maps which use `CMD +` and `CMD -`. I have added these as defaults.
A dedicated re-center button (`CMD 0`) is useful when the map was moved or zoomed, to quickly get back to the current location.
`CMD +` for Zoom In (With a hidden alternative of CMD = to also make it work on non numeric keyboards without much confusion.
`CMD -` for Zoom Out
`CMD 0` for recentering the map.
The **original zoom in and zoom out** on the arrow keys are still active but not shown in the help popup when holding down CMD for …

Add more keyboard shortcuts

---

Sources/Voice/OATTSCommandPlayerImpl.mm

This PR tries to use the Apple provided enhanced voices (these have to be manually downloaded by a user in devices settings [Settings -> Accessibility -> Voice Over -> Speech -> Voice])
This change will make the app search for enhanced voices that are available for the chosen language first before defaulting to the previously chosen voices.
Let me know if there's any changes I should make to improve this PR or if there's a guide I've missed to adhere to standards e.t.c.

Added in support for enhanced voices

---

Resources/Resources.storyboard

fix map details cell

---

OsmAnd Maps copy-Info.plist
Resources/OsmAnd-Info.plist
Sources/Controllers/2.0/OAFavoriteListViewController.mm
Sources/Controllers/2.0/OAGPXItemViewController.mm
Sources/Controllers/2.0/RoutePlanning/OASaveTrackBottomSheetViewController.mm

Switching the import and export UTIs from `net.osmand.gpx` to the more generic `com.topografix.gpx`.
Other Apps could get into trouble when they register the generic UTI, but apple reserves `net.osmand.gpx` for `.gpx` files because OsmAnd is installed. I recognized this on my own App, which led to bad App Store reviews and other Apps that try to register for the generic UTI might run into the same issue. Please let me know if this PR makes sense and I also can extend this for the other file types that are registered in OsmAnd.
The problems that occured were, that the `UIDocumentPickerViewController` didn't recognize the `.gpx` files at all and the **Share Extension** recognized the files, but didn't read the contents of it. My work around was to support the generic UTI as well as the …

Support generic GPX Uniform Type Identifier

---

Sources/Controllers/Map/Widgets/OATextInfoWidget.mm

https://github.com/osmandapp/OsmAnd-iOS/issues/1454
Before:
https://www.dropbox.com/s/enu0y1i4s4v6mlv/Screen%20Recording%202021-08-25%20at%2010.17.35.mov?dl=0
After:
https://www.dropbox.com/s/7i5ib1h56xktwy5/Screen%20Recording%202021-08-25%20at%2010.22.12.mov?dl=0
How to reproduce:
Turn on max speed widget.
Start navigation from  48.45075 22.68769   to    48.73547 22.48596
Text disappears here:  48.46020 22.64747

fix speed widget text bug

---

Sources/Controllers/QuickAction/OAQuickActionHudViewController.mm

[Issue](https://github.com/osmandapp/OsmAnd-iOS/issues/1730)
[Icon moving video](https://www.dropbox.com/s/coostbb8sl6lt6b/Screen%20Recording%202022-02-01%20at%2018.35.16.mov?dl=0)
If the saved icon coordinate is outside the screen boundary, it will be reset to the default value.

fix quick action button position

---

Sources/Controllers/TargetMenu/GPX/TrackMenu/OATrackMenuHudViewController.mm

[gpx file](https://www.dropbox.com/s/ewaja5ixiw9ue6p/Venice.gpx?dl=0)

gpx with metadata links crash fix

---

Sources/Controllers/Map/Widgets/OACurrentStreetName.mm

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/2014)
[video](https://www.dropbox.com/s/inbf7zovldq3ugv/Screen%20Recording%202022-06-29%20at%2023.18.04.mov?dl=0)

fix turn icon in street name widget

---

Sources/Controllers/TargetMenu/Search/OAQuickSearchViewController.mm

[issue Stresa](https://github.com/osmandapp/OsmAnd/issues/14983)
Part 1 Search results order.
Skipped. Because order in iOS and Androis is laready the same
Part 2 - Disappeared button
Before - without button
Now - with button
Synced this code from Android:
https://github.com/osmandapp/OsmAnd/blob/238a37c1e4640b8f4c7a2a646ee2005399f46e65/OsmAnd/src/net/osmand/plus/search/QuickSearchDialogFragment.java#L1970
---
[issue Milano](https://github.com/osmandapp/OsmAnd-iOS/issues/2140)
Also this PR fixed that issue

fix show on map button

---

Sources/Controllers/ChoosePlan/Views/OASubscriptionCardView.mm

Fix: description text is not fit on iPhone 13 mini

---

Sources/Controllers/Map/Layers/OAContextMenuLayer.mm
Sources/POI/OAPOI.h
Sources/POI/OAPOI.mm
Sources/Views/OATargetPointView.mm

[issue](https://github.com/osmandapp/OsmAnd-Issues/issues/1231)
Before/afrer:
50.41304° N, 30.52062° E
50.43162,30.51254

parking icons fix

---

Sources/OsmEdit/OAOpenStreetMapLocalUtil.mm

[Issue](https://github.com/osmandapp/OsmAnd-iOS/issues/2522)
[Synced with this android code](https://github.com/osmandapp/OsmAnd/commit/5b19f5cc352e463594cdc57a5cafffc4ea492096#diff-c378fa155710cade99bd6d5f0e239aed7b7e66feff134008a4d9c52fa0baa5aaR135)
before / after:

fix on offline osm editing name reading

---

Resources/Localizations/de.lproj/Localizable.strings

Hi, while using OsmAnd on iOS in German I noticed some typos and found a few more while fixing the others. :)
I also noticed that the strings are switching between the informal "Du" and the formal "Sie". Is that intended?

chore: Fix some typos in German translation

---

Sources/Helpers/OAOsmAndFormatter.mm

[issue](https://github.com/osmandapp/OsmAnd-Issues/issues/2074)
imported setting:
Before. App lang: English
After. App lang: English
After. App lang: Arabic

arabic numbers fixed

---

Sources/Controllers/TravelGuides/data/OATravelLocalDataDbHelper.mm
Sources/Controllers/TravelGuides/data/TravelLocalDataHelper.swift

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/3459)
Fixed bug with saving and reading article gpx points.
Also fixed bug with deleting saved article.
Screenshot of opened saved article without any travel guides files. All points are available.

travel_guides_poits_saving_bug

---

Sources/Controllers/TargetMenu/OATransportStopsBaseController.h
Sources/Controllers/TargetMenu/OATransportStopsBaseController.mm
Sources/Controllers/TargetMenu/Transport/OATransportStopViewController.mm

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/3647)
Before - Bus icon on IOS. Subway icon on Android
After - Subway icon on IOS and Android
---
Before
After
---
Synced this code

subway icon fix

---

Sources/Controllers/TargetMenu/GPX/TrackMenu/OATrackMenuHudViewController.mm

https://github.com/osmandapp/OsmAnd-iOS/issues/3729
`OsmAnd Maps: UIKitCore: -[UINavigationController _setViewControllers:transition:animated:operation:] + 364`
video before (long tryin to reproduce crash)
https://github.com/osmandapp/OsmAnd-iOS/assets/35684515/71d8e76d-fbc9-40a1-a5be-f8c3f7fd3a89
video after
https://github.com/osmandapp/OsmAnd-iOS/assets/35684515/bbf55194-7f35-4e8d-b8f3-df36fa329679

47_crashfix_tracksList

---

Sources/Controllers/Settings/NavigationSettings/OAVehicleParametersSettingsViewController.mm

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/3729)
`OsmAnd Maps: UIKitCore: UIViewCommonInitWithFrame + 1256`
before
https://github.com/osmandapp/OsmAnd-iOS/assets/35684515/c446de47-4da2-4de3-9625-9633b0b17264
after

47_crashfix_truckVehicleParams

---

Sources/Router/OATargetPointsHelper.mm

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/3729)
`OsmAnd Maps: -[OATargetPointsHelper getLocationName:] + 64`
Can't reproduce. But this line from crashlog can crash only if location is nil. So I added a check for it.

47_crashfix_locationName

---

Sources/Controllers/RoutePlanning/OARoutePlanningHudViewController.mm
Sources/Controllers/TargetMenu/GPX/TrackMenu/OATrackMenuHudViewController.mm
Sources/Helpers/OAUtilities.h
Sources/Helpers/OAUtilities.m

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/3729)
`OsmAnd Maps: -[OATrackMenuHudViewController createUniqueFileName:path:] + 256`
video:
https://github.com/osmandapp/OsmAnd-iOS/assets/35684515/311e0769-6780-44e3-89d5-d2c923ba20ae

47_crashfix_createUniqueFileName

---

Sources/Backup/OANetworkSettingsHelper.m

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/3729)
`OsmAnd Maps: -[OASyncBackupTask downloadRemoteVersion:filesType:shouldReplace:restoreDeleted:] + 156`
Can't reproduce crash. But looking to code of crashed function it seems it can crash on creation an array with nil element. So I added a check for it.

47_crashfix_downloadRemoteVersion

---

Sources/POI/OAPOI.mm

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/3711)
Before
After
filenames:

fix_subway_icon_in_search

---

Sources/Controllers/DashboardOnMap/MapSettings/OAWeatherLayerSettingsViewController.mm
Sources/Controllers/Map/Layers/OAWeatherRasterLayer.mm

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/3779)
video before (r4.8) - opacity slider doesn't work at all. The same bug exists in android. Created [issue](https://github.com/osmandapp/OsmAnd/issues/20533) for them.
https://github.com/user-attachments/assets/4288a844-1044-4ee7-bdec-477ce972d4bd
video before (master) - opacity slider works but layer blinks
https://github.com/user-attachments/assets/db1c6906-1979-4298-a1d1-59b175088ff2
video after fix - slider works. layer doesn't blink
https://github.com/user-attachments/assets/5748eb72-f35a-4035-89bf-9eeddbf1c643

Weather alpha changing fix

---

Sources/Controllers/Map/Widgets/OALanesControl.mm
Sources/Controllers/Map/Widgets/OAMapWidgetRegistry.mm
Sources/Controllers/Map/Widgets/OATopTextView.mm
Sources/Helpers/OAAppSettings.h
Sources/Helpers/OAAppSettings.m

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/3845)
In this request I deleted old unused settings, that was stored but never changed. No one set method, no one call from UI. So it was always with default values. 
In android this settings also not used. I think they also forgot to delete it.
So I deleted it. Now widgets visibility state sets only here. 
---
Testing with this widget settings. For Car and Walking profiles.
Testing Car profile 
https://github.com/user-attachments/assets/baf4d9f2-9175-48bc-a99c-a614f8e4932a
Testing Walking profile - widgets on
https://github.com/user-attachments/assets/52a7118b-f61c-4736-b104-c288a12ee77f
Testing Walking profile - widgets off
https://github.com/user-attachments/assets/44fc3fa9-419e-4326-84c6-c171419bcd70
---

pedestrian top widget fix. removes old unused settings

---

Sources/Controllers/Map/Layers/OAMyPositionLayer.mm

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/3927)
Before:
https://github.com/user-attachments/assets/bbdf4b89-5edb-46a1-acce-b96cf92b1f80
After:
https://github.com/user-attachments/assets/4bd61552-580d-4e76-81ea-0e6a4ec1f272

white_3d_icon_fix

---

Sources/Controllers/Map/OAMapViewController.mm
Sources/Helpers/OAZoom.h
Sources/Helpers/OAZoom.m

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/3965)
before / after
fist app launch also use this formula
https://github.com/user-attachments/assets/0dda83fc-25dd-4769-9400-ca5ea3f31424

add minimal zoom calculation formula for current screen

---

Sources/Controllers/Resources/OADonationSettingsViewController.mm
Sources/Plugins/Monitoring/OAMonitoringPlugin.mm
Sources/Plugins/NauticalMapsPlugin/OANauticalMapsPlugin.m
Sources/Plugins/OsmEditing/OAOsmEditingPlugin.mm
Sources/Plugins/SRTMPlugin/OASRTMPlugin.mm
Sources/Plugins/Weather/OAWeatherPlugin.mm
Sources/Purchases/OAProducts.mm

Looks like somebody accidentally used NSLocalizedString() instead of OALocalizedString(). Fixed.
before/after

fix En_GB translation bug

---

Sources/Controllers/Map/OAMapViewController.mm
Sources/Helpers/OAZoom.h
Sources/Helpers/OAZoom.m

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/3965)
Previous min zoom was 1 beause of rounding down. Make it rounding up.
before:
https://github.com/user-attachments/assets/f37ddd63-b0dc-4e02-81f6-4d88e8834691
after:
https://github.com/user-attachments/assets/40003eae-3b20-4a73-a134-7cb84a8d4e4b

Min_zoom_fix_2

---

Sources/Controllers/Map/OAMapHudViewController.mm

ios before. north isn't up:
https://github.com/user-attachments/assets/e4464063-eac2-472a-836b-b43a4e66801e
ios after. north is up:
https://github.com/user-attachments/assets/9c7147be-85d7-4660-b81d-4b7364257440
how it works in android. north is up::
https://github.com/user-attachments/assets/c7165036-e28c-48f0-887d-0729f5f787e3

fix non resetting map angle by compass btn click

---

Sources/FirstUsage/OAFirstUsageWizardController.mm
Sources/SwiftExtensions/UIFont+Extension.swift
Sources/Views/OATargetPointView.mm

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/2222)
<table style="width:100%">
<tr>
<th>before</th>
<th>after</th>
</tr>
<tr>
<td><video src="https://github.com/user-attachments/assets/9a24e2d8-a5c6-4b99-a0da-cf3af3bb0165"  width="300" height="auto"/> </td>
<td><video src="https://github.com/user-attachments/assets/82e45cdb-dcac-4c13-9604-03b0d7fb2cd8"  width="300" height="auto"/> </td>
</tr>
</table>  
<table style="width:100%">
<tr>
<th>before</th>
<th>after</th>
</tr>
<tr>
<td><video src="https://github.com/user-attachments/assets/184aeb56-ea5e-4559-9467-ee3cc323b58a"  width="300" height="auto"/> </td>
<td><video src="https://github.com/user-attachments/assets/a494217e-f337-44f3-baf6-d58eb31ce340"  width="300" height="auto"/> </td>
</tr>
</table>

add monospaced digits font to another downloading screens

---

Sources/Controllers/Map/Layers/OAFavoritesLayer.mm
Sources/Controllers/Map/Layers/OAGPXLayer.mm
Sources/Controllers/Map/Layers/OAOsmEditsLayer.mm
Sources/Controllers/TargetMenu/PointEditing/OAGpxWptEditingHandler.mm
Sources/GPX/OAGPXDocumentPrimitives.h
Sources/Helpers/OAFavoritesHelper.mm
Sources/Models/OAFavoriteItem.mm
Sources/Models/OAGpxWptItem.mm

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/4207)
crash:  OsmAnd Maps: +[OAFavoritesHelper getCompositeIcon:backgroundIcon:color:] + 80
Can't reproduce. I just added initing with default values from another getCompositeIcon() method. I think it should fix the problem.

fix getCompositeIcon crash

---

Sources/Controllers/Map/Widgets/OATopTextView.mm
Sources/Views/XibViews/OATopTextView.xib

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/4184)
With Ref before/after (fixed)
Without Ref before/after (no changes)
Navigation from 
48.14183° N, 13.99145° E     
to   
48.14850 13.97646

street name widget ref overlay fix

---

Sources/Controllers/TargetMenu/Favorites/OAFavoriteViewController.mm
Sources/Controllers/TargetMenu/GPX/OAGPXWptViewController.mm
Sources/Controllers/TargetMenu/PointEditing/OAFavoriteEditingHandler.mm
Sources/Controllers/TargetMenu/PointEditing/OAGpxWptEditingHandler.mm
Sources/POI/OAPOI.mm

[issue](url)
Don't write to file amenity_origin tag if it is empty.
Tags - before:
Tags - after:
---
Context menu fix.
Original POI:
Waypoint without map - before:
Waypoint without map - after:

Wpt tags fix

---

Sources/Controllers/TargetMenu/PointEditing/OAGpxWptEditingHandler.mm

[issue](https://github.com/osmandapp/OsmAnd-Issues/issues/2869#issuecomment-2631306907)
adding point with empty fields
before:
after:

wpt empty tags fix

---

Sources/Controllers/TargetMenu/POI/OAPOIViewController.mm

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/4334)
video: 
https://github.com/user-attachments/assets/445d04d4-6bae-4154-9e9e-cda6ae162e75

always show detail screen for long text in context menu

---

Sources/Controllers/Cells/OACollectionSingleLineTableViewCell.m

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/3942#issuecomment-2782751569)
video before:
when nautical row appears it for a while shows icons from disappearing at top row.
https://github.com/user-attachments/assets/de2d4031-ab64-470c-8d62-008e849cab49
---
video after: 
nautical row appears without lags.
https://github.com/user-attachments/assets/8c6af08f-f23d-440e-b325-77fe2ac79483

poi_component_fix_nautical_row_blinking

---

Sources/Controllers/Resources/OAManageResourcesViewController.mm
Sources/Helpers/DownloadingCellHelper/DownloadingCellBaseHelper.swift
Sources/Views/OAFreeMemoryView.h
Sources/Views/OAFreeMemoryView.m

Added `freeMemoryView` reload during `updateContent`. 
Clear `statuses` and `progresses` during `cleanCellCache` so that cells are configured during reload.
Added `tableView.reloadData` when deleting a map with a swipe.
video after fix:
https://github.com/user-attachments/assets/f4f66083-1857-468e-b7b2-fbce216acede

Рage in Maps and Resources is not updated after downloading the map

---

Sources/Helpers/OALocationParser.mm

The problem was that NSString.length is NSUInteger. When the value is less than DIGITS_AFTER_COMMA the difference is negative and the loop reaches NSUIntegerMax iterations.

Endless spinner rotation in Maps & Recouces search

---

Sources/Controllers/Map/Layers/OAPOILayer.mm

Item from issue [Click on Relation POIs: issue with clicks on university POIs](https://github.com/osmandapp/OsmAnd/issues/21993):
_Bug that relation close to original object was not found in POI - search radius should be increased_
Code porting [from Android](https://github.com/osmandapp/OsmAnd/blob/64282a2ab7c9b061462c6ea8135f41fc45463214/OsmAnd/src/net/osmand/plus/views/layers/MapSelectionHelper.java#L721)

[5.0] Increase radius for POI from relation

---

Sources/POI/OAPOIHelper.mm

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/4642)
before / after
---

travel_guides_fix

---

Sources/Controllers/Map/Widgets/OATextInfoWidget.mm
Sources/Helpers/OAUtilities.h
Sources/Plugins/ExternalSensorsPlugin/BLE/BLEManager/Devices/Device.swift
Sources/Plugins/ExternalSensorsPlugin/BLE/DeviceHelper.swift

- Replaced direct NSString comparisons with NSStringsEqual(_Nullable a, _Nullable b)
to safely handle nil values.
- Fixes crash caused by redundant updates in the widget panel when _subtext or text is nil.
- Fix crash: addObservers

crash fixes

---

Sources/Controllers/Map/Helpers/OAMapSelectionHelper.mm
Sources/Controllers/Map/Layers/OAOsmBugsLayer.mm
Sources/Core/OAOsmNotesMapLayerProvider.h
Sources/Core/OAOsmNotesMapLayerProvider.mm

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/4853)
Before - Testflight r5.0:
Before - master:
After - fix:

osm_online_note_contex_menu_fix

---

Sources/Controllers/Panels/OAMapPanelViewController.h
Sources/Controllers/Panels/OAMapPanelViewController.mm
Sources/Controllers/TargetMenu/Search/OAQuickSearchViewController.mm

[issue](https://github.com/osmandapp/OsmAnd/issues/22089#issuecomment-3233847418)
before: "turm de sinne" -> "sinne" 
after: "turm de sinne" -> "turm de sinne" 
video:
https://github.com/user-attachments/assets/fac4aad6-60d9-40c4-a0c6-778802cb5ea9
test point:
49.452215 11.069502
https://www.openstreetmap.org/node/1539266304#map=19/49.452215/11.069502
test phrase:
"turm de sinne"

Fix search querry resetting
