osmandapp/OsmAnd-iOS

Sources/Controllers/2.0/OAFavoriteImportViewController.mm
Sources/Controllers/2.0/OAFavoriteListViewController.mm

Added Replace All button to Import Favorites functionality
Added Cancel button to Rename/Replace/Ignore Import dialog
Added Cancel button to Rename dialog

Fixes - Import Favorite

---

Resources/en.lproj/Localizable.strings

Is this the right place to fix the typos so that they are also picked up in Weblate for translation?

Fix some typos in Localizable.strings

---

Resources/en.lproj/Localizable.strings

Fix typo in "Participiate"

---

Resources/en.lproj/Localizable.strings

Fix typo "Coloses at:"

---

Resources/en.lproj/Localizable.strings

Fix multiple strings on a row, which create problems at Weblate translation system.

Fix multiple strings on a row

---

OsmAnd.xcodeproj/project.pbxproj
Resources/Controllers/Cells/OABottomSheetHeaderIconCell.xib
Resources/Controllers/Cells/OADescrTitleCell.xib
Resources/Controllers/Cells/OAImageCardCell.xib
Resources/Controllers/Cells/OAMapillaryNoImagesCell.xib
Resources/en.lproj/Localizable.strings
Sources/Cards/OAImageCard.m
Sources/Cards/OANoImagesCard.m
Sources/Controllers/2.0/BottomSheet/MapillaryBottomSheet/OAInstallMapillaryBottomSheetViewController.h
Sources/Controllers/2.0/BottomSheet/MapillaryBottomSheet/OAInstallMapillaryBottomSheetViewController.mm
Sources/Controllers/Cells/OABottomSheetHeaderIconCell.h
Sources/Controllers/Cells/OABottomSheetHeaderIconCell.m
Sources/Controllers/Cells/OAImageCardCell.h
Sources/Controllers/Cells/OAImageCardCell.mm
Sources/Controllers/Cells/OAMapillaryNoImagesCell.mm
Sources/Plugins/Mapillary/OAMapillaryPlugin.h
Sources/Plugins/Mapillary/OAMapillaryPlugin.mm
Sources/Plugins/OAPlugin.mm
Sources/Purchases/OAProducts.h

Added getMapillary bottomsheet, finished image cards begavior + added mapillary addon with configure screen item

---

Resources/OsmAnd-Info.plist
Resources/en.lproj/Localizable.strings
Sources/AppHost/OAAppDelegate.mm
Sources/Controllers/2.0/OASettingsViewController.h
Sources/Controllers/2.0/OASettingsViewController.m
Sources/Controllers/OARootViewController.m
Sources/Helpers/OAAppSettings.h
Sources/Helpers/OAAppSettings.m

Hi,
I'm one of the developers of the [WunderLINQ](http://www.wunderlinq.com). The WunderLINQ enables you to use your motorcycle's handlebar controls to control your smartphone. Essentially the device acts as a Bluetooth keyboard.
My patch to the Android version was [merged](https://github.com/osmandapp/Osmand/pull/7000) recently, this is the iOS equivalent
Here is a video of the integration in action: [https://youtu.be/gTXtVagOQqk](https://youtu.be/gTXtVagOQqk)

Add support for WunderLINQ, motorcycle smartphone control.

---

Resources/ru.lproj/Localizable.strings
Sources/Controllers/2.0/Routing/OARoutingSettingsCell.mm
Sources/Views/OATargetPointView.mm

russian: string "shared_string_on" was missing;
resizing: titleLabel.text works incorrect, takes previous name. currentTitle is better.

sound button

---

Resources/en.lproj/Localizable.strings

add translations

---

Sources/Controllers/2.0/MyPlaces/MyPlaces.storyboard
Sources/Controllers/2.0/OAFavoriteListViewController.mm

+ Extra space at top of the table removed

Selection of cell in editing mode changed.

---

Sources/Controllers/Map/OAMapHudViewController.mm
Sources/Views/OAOverlayUnderlayView.h
Sources/Views/OAOverlayUnderlayView.m

https://github.com/osmandapp/OsmAnd-iOS/issues/752
Screenshots
https://www.dropbox.com/sh/355k8r9k3hhou89/AAB8J4WFU6X01Bfn2y3drLIra?dl=0

Aligned the slider centrally and set it to a fixed width.

---

Sources/Controllers/2.0/OADirectionsCardController.mm

https://github.com/osmandapp/OsmAnd-iOS/issues/726

fix crash with markers deleting

---

Resources/en.lproj/Localizable.strings
Sources/Controllers/2.0/BottomSheet/OABottomSheetViewController.xib
Sources/Controllers/2.0/BottomSheet/PublicTransportOptionsBottomSheet/OAPublicTransportOptionsBottomSheet.h
Sources/Controllers/2.0/BottomSheet/PublicTransportOptionsBottomSheet/OAPublicTransportOptionsBottomSheet.mm
Sources/QuickAction/Actions/OAShowHideTransportLinesAction.mm

https://github.com/osmandapp/OsmAnd-Issues/issues/23

Transport switch fix

---

Sources/AppHost/OsmAndAppImpl.mm
Sources/Map/OAMapCreatorHelper.m

https://github.com/osmandapp/OsmAnd-iOS/issues/707
Backup folder compare
https://www.dropbox.com/sh/e6hj5nqyku3srsr/AABQkGtLF22GIrfhUttFcdaBa?dl=0

Exclude sqlitedb user files from apple backup

---

Sources/Views/OATargetPointView.mm

https://github.com/osmandapp/OsmAnd-iOS/issues/724
Sharing without image. But with text in format "Name - GroupName - Description - Url"
Screenshot:
https://www.dropbox.com/s/hmc3dlo6brjkm1a/scr.png?dl=0

edit sharing favorites poi

---

Resources/Controllers/Cells/OAMultiIconTextDescCell.xib
Sources/Controllers/2.0/Settings/OAGlobalSettingsViewController.m

https://github.com/osmandapp/OsmAnd-Issues/issues/48
screenshots
https://www.dropbox.com/sh/kvnzfktvwtmi4to/AAAykBceq2oVzD6mf2kMcstna?dl=0

ui fix for GlobalSettings

---

OAPreviewZoomLevelsCell.xib
Resources/Controllers/DownloadMapSource/OADownloadMapProgressViewController.mm
Resources/Controllers/DownloadMapSource/OADownloadMapProgressViewController.xib
Resources/Controllers/DownloadMapSource/OADownloadMapViewController.mm
Sources/Controllers/Cells/OAPreviewZoomLevelsCell.m
Sources/OAPreviewZoomLevelsCell.h

https://github.com/osmandapp/OsmAnd-Issues/issues/14

Download tiles screen UI fix

---

Sources/Controllers/2.0/Settings/GeneralSettings/OAProfileGeneralSettingsViewController.m

https://github.com/osmandapp/OsmAnd-Issues/issues/30
screenshots
https://www.dropbox.com/sh/c803ab5vcg1o22s/AAACjd3P0cfa2hct9SKZ_LJ1a?dl=0

fix footer view offset in GeneralSettings

---

Sources/Controllers/2.0/OAGPXItemViewController.mm
Sources/Controllers/2.0/OAGPXListViewController.mm
Sources/Controllers/OARootViewController.m

https://github.com/osmandapp/OsmAnd-iOS/issues/769

fix opening GPX as XML from GoogleDrive

---

Resources/Controllers/Cells/OAIconTextDescCell.xib
Resources/Controllers/Cells/OATitleRightIconCell.xib
Sources/Controllers/2.0/Settings/OABaseSettingsViewController.xib
Sources/Controllers/2.0/Settings/OAOsmAccountSettingsViewController.m
Sources/Controllers/2.0/Settings/OAOsmEditingSettingsViewController.mm
Sources/Controllers/2.0/Settings/OAOsmEditingSettingsViewController.xib
Sources/Controllers/2.0/Settings/OATripRecordingSettingsViewController.mm

https://github.com/osmandapp/OsmAnd-Issues/issues/64

Settings fot plugin ui fix

---

Resources/Controllers/Cells/OAIconTextDescSwitchCell.xib
Sources/Controllers/2.0/Settings/OAMainSettingsViewController.m
Sources/Controllers/Cells/OAIconTextDescSwitchCell.h
Sources/Controllers/Cells/OAIconTextDescSwitchCell.m

https://github.com/osmandapp/OsmAnd-Issues/issues/47

Settings main screen ui fix2

---

Sources/Controllers/2.0/OACollapsableCoordinatesView.mm
Sources/Controllers/2.0/OAEditTargetViewController.mm
Sources/Controllers/2.0/OATargetMenuViewController.h
Sources/Views/OATargetPointView.mm

https://github.com/osmandapp/OsmAnd-iOS/issues/720

Fix navbar blinking and cell height

---

Sources/Controllers/2.0/OAPOIViewController.mm

https://github.com/osmandapp/OsmAnd-iOS/issues/538
screenshot:
https://www.dropbox.com/s/jf6p9krbq01igfh/simulator%20screen%20shot%20-%20iphone%205s%20-%202020-09-14%20at%2011.47.38.png?dl=0

hide images tags in PoiVC

---

Resources/Controllers/Cells/OATitleRightIconCell.xib
Sources/Controllers/2.0/BottomSheet/SettingsActionBottomSheet/OADeleteProfileBottomSheetViewController.h
Sources/Controllers/2.0/BottomSheet/SettingsActionBottomSheet/OADeleteProfileBottomSheetViewController.m
Sources/Controllers/2.0/Settings/OAConfigureProfileViewController.m

Settings action

---

Sources/Controllers/2.0/OAGPXItemViewController.mm
Sources/Views/OATargetPointView.mm

https://github.com/osmandapp/OsmAnd-iOS/issues/804

fix attributed string breaking

---

Sources/Controllers/2.0/Routing/OARouteSettingsViewController.mm
Sources/Controllers/2.0/Settings/NavigationSettings/OAVehicleParametersViewController.mm

https://github.com/osmandapp/OsmAnd-Issues/issues/109

fix icons color

---

Sources/OsmEdit/OAOpenStreetMapRemoteUtil.mm

https://github.com/osmandapp/OsmAnd-iOS/issues/833
https://www.dropbox.com/s/h9yjse2etxfxeib/screenshot%202020-09-16%20at%2015.34.19.png?dl=0

fix coordinates rounding bug

---

Sources/OsmEdit/OAOpenStreetMapRemoteUtil.mm

https://github.com/osmandapp/OsmAnd-iOS/issues/845

add version to user agent

---

Resources/Controllers/Cells/OAIconTextCell.xib

https://github.com/osmandapp/OsmAnd-iOS/issues/826

Fix MyFavorites constraints

---

Sources/Controllers/2.0/Settings/OAMainSettingsViewController.m

https://github.com/osmandapp/OsmAnd-Issues/issues/154

fix not clicable area under hidden switch

---

OAAppVersionDependedConstants.h
OAAppVersionDependedConstants.m
OsmAnd.xcodeproj/project.pbxproj
Resources/en.lproj/Localizable.strings
Sources/AppHost/OsmAndAppImpl.mm
Sources/Controllers/2.0/BottomSheet/WhatsNewBottomSheet/OAWhatsNewBottomSheetViewController.h
Sources/Controllers/2.0/BottomSheet/WhatsNewBottomSheet/OAWhatsNewBottomSheetViewController.m
Sources/Controllers/Help/OAHelpViewController.mm
Sources/Controllers/Map/OAMapViewController.mm
Sources/Controllers/OARootViewController.m
Sources/Helpers/OAAppSettings.h
Sources/Helpers/OAAppSettings.m

https://github.com/osmandapp/OsmAnd-iOS/issues/897

Add What's new screens

---

Resources/Controllers/Cells/OAMenuSimpleCellNoIcon.xib
Sources/Controllers/Help/OAHelpViewController.mm

https://github.com/osmandapp/OsmAnd-Issues/issues/322

fixing help menu cells layout bug

---

Sources/OAWorldRegion.mm
Sources/Purchases/OAProducts.mm

https://github.com/osmandapp/OsmAnd-Issues/issues/166

made antarctica free and without banner

---

Sources/Controllers/2.0/Settings/OAProfileAppearanceViewController.mm

https://github.com/osmandapp/OsmAnd-iOS/issues/960

Fix icon unchanging bug with turned off custom profiles

---

OAAppVersionDependentConstants.h
OAAppVersionDependentConstants.m
OsmAnd.xcodeproj/project.pbxproj
Sources/Controllers/2.0/BottomSheet/WhatsNewBottomSheet/OAWhatsNewBottomSheetViewController.m
Sources/Controllers/Help/OAHelpViewController.mm

https://github.com/osmandapp/OsmAnd-Issues/issues/339

add new icons2

---

Sources/Helpers/OAAppSettings.h
Sources/Helpers/OAAppSettings.m
Sources/OAApplicationMode.m

https://github.com/osmandapp/OsmAnd-iOS/issues/900

fix default profile reseting

---

Sources/Controllers/2.0/OAQuickActionListViewController.m
Sources/Controllers/2.0/OAQuickActionListViewController.xib

https://github.com/osmandapp/OsmAnd-Issues/issues/359

add done and cancel buttons to quick action editing list

---

Sources/Controllers/Map/Widgets/OADestinationsLineWidget.mm

https://github.com/osmandapp/OsmAnd-iOS/issues/990
Screenshots before/after:
https://www.dropbox.com/s/qhu76xifxihg6ym/Screenshot%202020-12-18%20at%2021.06.01.png?dl=0
https://www.dropbox.com/s/fixgrep635564is/Screenshot%202020-12-18%20at%2021.24.50.png?dl=0

made thicker dashed line to marker

---

Sources/Controllers/2.0/Routing/OARoutingSettingsCell.mm

https://github.com/osmandapp/OsmAnd-Issues/issues/373

fix not workin roution voice on/off button

---

Resources/en.lproj/Localizable.strings

https://hosted.weblate.org/translate/osmand/ios/en/?checksum=ec5588e6d4d7f3f6#comments

Typo: "suppotred" --> "supported"

---

Sources/Controllers/2.0/Settings/OAImportSettingsViewController.mm

https://github.com/osmandapp/OsmAnd-Issues/issues/399

Fix profile importing crash

---

Resources/Controllers/Cells/OARouteInfoAltitudeCell.xib

https://github.com/osmandapp/OsmAnd-iOS/issues/1007

Fix track detail lablels ovelaping

---

OASizes.h
Sources/Controllers/2.0/Settings/NavigationSettings/OARoadSpeedsViewController.mm
Sources/Controllers/2.0/Settings/OABaseSettingsViewController.h
Sources/Controllers/2.0/Settings/OABaseSettingsViewController.m
Sources/Controllers/2.0/Settings/OABaseSettingsViewController.xib

https://github.com/osmandapp/OsmAnd-iOS/issues/802
1. Made NavBar height = 64px in modal mode in all similar screens. (before/after)
2. Disabled all gestures on slider touch. (before/after)
https://www.dropbox.com/s/6y1we5xa7tb7kja/Screen%20Recording%202021-01-12%20at%2023.23.59.mov?dl=0
https://www.dropbox.com/s/0ug0mb5n6pgjzje/Screen%20Recording%202021-01-12%20at%2023.25.11.mov?dl=0

Minmax UI fix

---

Sources/Controllers/2.0/Routing/OARouteSettingsBaseViewController.mm
Sources/Controllers/2.0/Settings/NavigationSettings/OAProfileNavigationSettingsViewController.mm
Sources/Controllers/2.0/Settings/OABaseSettingsViewController.m

https://github.com/osmandapp/OsmAnd-iOS/issues/970

Increase navbar height. Add refreshing to options screen

---

Sources/POI/OAPOIUIFilter.mm
Sources/Search/OASearchCoreFactory.h
Sources/Search/OASearchCoreFactory.mm
Sources/Search/OASearchUICore.h
Sources/Search/OASearchUICore.mm

https://github.com/osmandapp/OsmAnd-iOS/issues/958

Search fix

---

Sources/Controllers/Map/OAMapInfoController.mm
Sources/Views/OAUserInteractionPassThroughView.h
Sources/Views/OAUserInteractionPassThroughView.m

before
https://www.dropbox.com/s/7fzvt1rjz04opsx/Screen%20Recording%202021-01-27%20at%2008.21.59.mov?dl=0
after
https://www.dropbox.com/s/n4g6w74hep5yoh8/Screen%20Recording%202021-01-27%20at%2008.23.53.mov?dl=0

trying to fix widgets overlapping

---

OAGPXTrackCell.xib
Sources/Controllers/2.0/RoutePlanning/OABaseTableViewController.xib
Sources/Controllers/2.0/RoutePlanning/OAOpenAddTrackViewController.mm

https://github.com/osmandapp/OsmAnd-Issues/issues/414

fix AddToTrack separators

---

Sources/Controllers/2.0/RoutePlanning/OAExitRoutePlanningBottomSheetViewController.m
Sources/Controllers/2.0/RoutePlanning/OAExitRoutePlanningBottomSheetViewController.xib

https://github.com/osmandapp/OsmAnd-Issues/issues/421

Plan Route Exit Dialog - ui fix

---

Sources/Controllers/2.0/Routing/OARoutePreferencesParameters.mm
Sources/Controllers/2.0/Settings/NavigationSettings/OAProfileNavigationSettingsViewController.mm
Sources/Controllers/2.0/Settings/NavigationSettings/OARouteParametersViewController.mm

https://github.com/osmandapp/OsmAnd-iOS/issues/970

fix not-updating settings view

---

Resources/Controllers/Cells/OATextInputFloatingCellWithIcon.xib
Sources/Controllers/2.0/OAAdvancedEditingViewController.mm
Sources/Controllers/2.0/OABasicEditingViewController.mm
Sources/Controllers/2.0/OAPoiTypeSelectionViewController.mm

https://github.com/osmandapp/OsmAnd-iOS/issues/888
video
https://www.dropbox.com/s/7jffvhfgavmtmwg/Screen%20Recording%202021-02-03%20at%2012.40.53.mov?dl=0

fix poi type search

---

Resources/en.lproj/Localizable.strings
Sources/Controllers/2.0/Settings/OAImportDuplicatesViewController.mm
Sources/Controllers/2.0/Settings/OAImportSettingsViewController.mm

https://github.com/osmandapp/OsmAnd-Issues/issues/399
android pr
https://github.com/osmandapp/OsmAnd/pull/10747/files
video
https://www.dropbox.com/s/sgzv1zo7kiqjveo/Screen%20Recording%202021-02-02%20at%2003.55.35.mov?dl=0
test file
https://www.dropbox.com/s/34jqht20oauqb9g/with_truck_Renamed.osf?dl=0

add default name for unnamed profiles

---

Resources/Controllers/Cells/OADescrTitleCell.xib
Sources/Controllers/2.0/BottomSheet/OsmEditingBottomSheet/OAUploadFinishedBottomSheetViewController.mm
Sources/Controllers/Cells/OADescrTitleCell.h

https://github.com/osmandapp/OsmAnd-Issues/issues/348

fix osm upload cell constraints

---

Sources/Controllers/2.0/RoutePlanning/OASaveTrackBottomSheetViewController.mm
Sources/Controllers/2.0/RoutePlanning/OASaveTrackBottomSheetViewController.xib
Sources/Controllers/2.0/RoutePlanning/OASaveTrackViewController.mm
Sources/Controllers/2.0/RoutePlanning/OASaveTrackViewController.xib

https://github.com/osmandapp/OsmAnd-Issues/issues/415

fix gpx sharing bug. ui fix

---

Sources/Controllers/2.0/BottomSheet/SettingsActionBottomSheet/OADeleteProfileBottomSheetViewController.m
Sources/OAApplicationMode.m

https://github.com/osmandapp/OsmAnd-Issues/issues/399
video:
https://www.dropbox.com/s/s4butfyozb566n7/Screen%20Recording%202021-02-19%20at%2011.00.43.mov?dl=0
test osf file:
https://www.dropbox.com/s/vl0kvd5c18mhrqf/trucktest.osf?dl=0
android pr:
https://github.com/osmandapp/OsmAnd/pull/10940

Profile default name 2

---

Sources/Controllers/2.0/RoutePlanning/OAOpenAddTrackViewController.mm

https://github.com/osmandapp/OsmAnd-Issues/issues/414

fix separator color 2

---

Resources/Controllers/Cells/OAGPXRouteRoundCell.xib
Resources/Controllers/Cells/OATitleIconRoundCell.xib
Sources/Controllers/2.0/BottomSheet/OABaseBottomSheetViewController.h
Sources/Controllers/2.0/BottomSheet/OABaseBottomSheetViewController.m
Sources/Controllers/2.0/BottomSheet/OABaseBottomSheetViewController.xib
Sources/Controllers/2.0/RoutePlanning/InitialRoutePlanningBottomSheetViewController.mm
Sources/Controllers/2.0/RoutePlanning/OAOpenAddTrackViewController.mm
Sources/Controllers/Cells/OAGPXRouteRoundCell.h
Sources/Controllers/Cells/OATitleIconRoundCell.h

https://github.com/osmandapp/OsmAnd-Issues/issues/363

Plan route start create  edit track 2

---

Sources/Controllers/Map/OAMapInfoController.mm
Sources/Controllers/Panels/OAMapPanelViewController.mm

https://www.dropbox.com/s/s0rtjfk29o2h1up/screenshot%202021-04-07%20at%2016.40.51.png?dl=0
https://www.dropbox.com/s/s0rtjfk29o2h1up/screenshot%202021-04-07%20at%2016.40.51.png?dl=0
https://www.dropbox.com/s/ua7tbz7eivjtj3x/screenshot%202021-04-07%20at%2016.41.38.png?dl=0

fix coordinate and markers widget layout

---

Resources/Controllers/Cells/OACustomSelectionCollapsableCell.xib
Sources/Controllers/2.0/Settings/ImportExport/OAImportSettingsViewController.mm

https://github.com/osmandapp/OsmAnd-Issues/issues/509

import screen ui review fix

---

Sources/AppHost/OsmAndAppImpl.mm
Sources/POI/OAPOIFiltersHelper.mm

https://github.com/osmandapp/OsmAnd-iOS/issues/1111

fix poi overlay saettings resetting

---

OsmAnd.xcodeproj/project.pbxproj
Resources/Controllers/Cells/OAPointCell.xib
Resources/Views/OATargetPointView.xib
Sources/Controllers/2.0/OAChangePositionViewController.h
Sources/Controllers/2.0/OAChangePositionViewController.mm
Sources/Controllers/2.0/OAChangePositionViewController.xib
Sources/Controllers/2.0/OAFavoriteImportViewController.mm
Sources/Controllers/2.0/OAFavoriteListViewController.mm
Sources/Controllers/2.0/OAFavoriteViewController.h
Sources/Controllers/2.0/OAFavoriteViewController.mm
Sources/Controllers/2.0/OAReplaceFavoriteViewController.mm
Sources/Controllers/Cells/OAPointTableViewCell.h
Sources/Controllers/Map/Layers/OAFavoritesLayer.mm
Sources/Core/OAFavoritesMapLayerProvider.h
Sources/Core/OAFavoritesMapLayerProvider.mm
Sources/Core/OAWaypointsMapLayerProvider.h
Sources/Core/OAWaypointsMapLayerProvider.mm
Sources/Models/OAFavoriteItem.h
Sources/Models/OAFavoriteItem.mm
Sources/Views/OATargetPointView.mm

https://github.com/osmandapp/OsmAnd-Issues/issues/543
before/after

add myltilayer fav icon method

---

Sources/Controllers/Cells/OATargetPointViewCell.mm

https://github.com/osmandapp/OsmAnd-Issues/issues/533

Icons fixes

---

Sources/Controllers/2.0/BottomSheet/OABaseBottomSheetViewController.h
Sources/Controllers/2.0/BottomSheet/OABaseBottomSheetViewController.m
Sources/Controllers/2.0/BottomSheet/RouteInfoBottomSheet/OAFollowTrackBottomSheetViewController.h
Sources/Controllers/2.0/BottomSheet/RouteInfoBottomSheet/OAFollowTrackBottomSheetViewController.mm
Sources/Controllers/2.0/RoutePlanning/OAOpenAddTrackViewController.mm
Sources/Controllers/2.0/Routing/OARouteSettingsBaseViewController.mm
Sources/Controllers/Map/OAMapViewController.mm
Sources/Controllers/Panels/OAMapPanelViewController.h
Sources/Controllers/Panels/OAMapPanelViewController.mm

https://github.com/osmandapp/OsmAnd-Issues/issues/434
animation:YES
https://www.dropbox.com/s/c3wibaclh9u0hj4/Screen%20Recording%202021-04-26%20at%2014.22.29.mov?dl=0
animation:NO
https://www.dropbox.com/s/p90p1eyig5yhjxm/Screen%20Recording%202021-04-26%20at%2014.25.07.mov?dl=0

Follow track UI fix

---

Sources/Controllers/2.0/OAPOIViewController.mm

https://github.com/osmandapp/OsmAnd-iOS/issues/1167
crashing poi
https://www.openstreetmap.org/node/8107747633

fixed crash with opening hours in wrong format

---

Sources/Controllers/2.0/OAGPXItemViewController.mm

https://github.com/osmandapp/OsmAnd-iOS/issues/1130
screenshots before/after:
https://www.dropbox.com/s/wiv28rh7h124bmv/Screenshot%202021-05-06%20at%2016.27.23.png?dl=0
https://www.dropbox.com/s/kluab0skdy6v8aa/Screenshot%202021-05-06%20at%2016.32.31.png?dl=0

gpx average speed label fix

---

OsmAnd.xcodeproj/project.pbxproj
Resources/Controllers/Cells/OADescrTitleCell.xib
Sources/Controllers/2.0/BottomSheet/OABaseBottomSheetViewController.h
Sources/Controllers/2.0/BottomSheet/OABaseBottomSheetViewController.m
Sources/Controllers/2.0/BottomSheet/WhatsNewBottomSheet/OAWhatsNewBottomSheetViewController.m

fix What's new bottom sheet

---

Resources/Controllers/Cells/OACustomSelectionCollapsableCell.xib
Sources/Controllers/2.0/Settings/ImportExport/OAExportItemsViewController.mm

https://github.com/osmandapp/OsmAnd-Issues/issues/509

Import new UI review2

---

Sources/Controllers/Map/OADestinationViewController.mm
Sources/Controllers/Map/OAMapHudViewController.mm
Sources/Controllers/Map/Widgets/OATopCoordinatesWidget.m
Sources/Controllers/Panels/OAMapPanelViewController.mm

https://github.com/osmandapp/OsmAnd-Issues/issues/424

Coordinate widget fix

---

Sources/Controllers/2.0/OAAddQuickActionViewController.m

broken icon fix

---

Resources/en.lproj/Localizable.strings
Sources/Controllers/Map/Layers/OAContextMenuLayer.mm

https://github.com/osmandapp/OsmAnd-Issues/issues/279

Android names convention

---

Sources/Controllers/2.0/OAEditGPXColorViewController.m
Sources/Controllers/2.0/OAGPXItemViewController.mm
Sources/Controllers/2.0/RoutePlanning/OASaveTrackViewController.mm
Sources/GPX/OAGPXDatabase.mm

https://github.com/osmandapp/OsmAnd-Issues/issues/598
video:
https://www.dropbox.com/s/5fbon08gchexqwz/screen%20recording%202021-05-19%20at%2022.02.41.mov?dl=0
And fix 2 ui bugs:
https://www.dropbox.com/s/1t58co7m9119b1g/Screen%20Recording%202021-05-20%20at%2017.25.54.mov?dl=0
https://www.dropbox.com/s/d4zh2j82kthktr6/Screen%20Recording%202021-05-20%20at%2017.43.53.mov?dl=0

remove extra track folder name in ui

---

Sources/GPX/OALoadGpxTask.m

https://github.com/osmandapp/OsmAnd-iOS/issues/1233
video:
https://www.dropbox.com/s/ju4zg1tdj85au5v/Screen%20Recording%202021-05-26%20at%2016.33.09.mov?dl=0

fix bug with *.GPX import

---

Sources/Core/OAFavoritesMapLayerProvider.mm
Sources/Core/OAWaypointsMapLayerProvider.mm

https://github.com/osmandapp/OsmAnd-Issues/issues/543
before:
https://www.dropbox.com/s/x7nv47u0tenril7/16.png?dl=0
after:
https://www.dropbox.com/s/gh8969c9v2wafyh/14.png?dl=0

decrease picture size in fav icons from 16px to 14px

---

Sources/Controllers/2.0/Routing/OARouteInfoView.mm

https://github.com/osmandapp/OsmAnd-iOS/issues/1235
video:
https://www.dropbox.com/s/x6pbsxog1itjjqq/Screen%20Recording%202021-05-27%20at%2012.04.47.mov?dl=0

fix broken swap start/destination button

---

Sources/Map/OAFileImportHelper.mm

https://github.com/osmandapp/OsmAnd-iOS/issues/1238
https://www.dropbox.com/s/4wa7gq39litl442/Screen%20Recording%202021-05-31%20at%2017.26.17.mov?dl=0

show imported OBF map

---

Sources/Controllers/2.0/Settings/ImportExport/OAExportItemsSelectionViewController.mm

https://github.com/osmandapp/OsmAnd-Issues/issues/622
before
after

fix wrong folder name on gpx export screen

---

Sources/Core/IOAMapTiledCollectionProvider.mm
Sources/Core/OAFavoritesMapLayerProvider.mm
Sources/Core/OAWaypointsMapLayerProvider.mm

https://github.com/osmandapp/OsmAnd-Issues/issues/543

use small bitmaps for small fav icons

---

Sources/Controllers/2.0/Settings/OAConfigureProfileViewController.m
Sources/Controllers/2.0/Settings/OAMainSettingsViewController.m
Sources/OAApplicationMode.m

https://github.com/osmandapp/OsmAnd-Issues/issues/483

review fix

---

Sources/Controllers/2.0/OACustomSourceDetailsViewController.mm
Sources/Controllers/2.0/Settings/ImportExport/OAPluginInstalledViewController.m
Sources/Controllers/2.0/Settings/ImportExport/OAPluginInstalledViewController.xib
Sources/Controllers/Resources/OAManageResourcesViewController.mm
Sources/Controllers/Resources/OAPluginDetailsViewController.mm
Sources/Helpers/OAUtilities.h
Sources/Helpers/OAUtilities.m

https://github.com/osmandapp/OsmAnd-Issues/issues/553

Ios packager review fix

---

OsmAnd.xcodeproj/project.pbxproj
Resources/Controllers/Cells/OAImagesCollectionViewCell.xib
Resources/Controllers/Cells/OAImagesTableViewCell.xib
Resources/Controllers/Cells/OAShapesCollectionViewCell.xib
Sources/Controllers/2.0/OACustomSourceDetailsViewController.mm
Sources/Controllers/Cells/OAImagesCollectionViewCell.h
Sources/Controllers/Cells/OAImagesCollectionViewCell.m
Sources/Controllers/Cells/OAImagesTableViewCell.h
Sources/Controllers/Cells/OAImagesTableViewCell.m

https://github.com/osmandapp/OsmAnd-Issues/issues/553
video:
https://www.dropbox.com/s/ddcdfm0van7wpn6/Screen%20Recording%202021-06-11%20at%2002.32.16.mov?dl=0

add multiple screenshots for plugins screen

---

Resources/Controllers/Cells/OAImagesTableViewCell.xib
Sources/Controllers/Cells/OAImagesTableViewCell.h
Sources/Controllers/Cells/OAImagesTableViewCell.m

https://www.dropbox.com/s/j94bs17lij9kf0l/Screen%20Recording%202021-06-16%20at%2020.26.50.mov?dl=0

add page control round indicators for images view cell

---

Sources/AppHost/OsmAndAppImpl.mm

https://github.com/osmandapp/OsmAnd-iOS/issues/1280
video:
https://www.dropbox.com/s/b0jbv4xiybbgqgb/Screen%20Recording%202021-06-22%20at%2022.08.21.mov?dl=0

turn off route simulation after restarting

---

Sources/Controllers/Map/Layers/OAGPXLayer.mm
Sources/Core/OAWaypointsMapLayerProvider.h

https://github.com/osmandapp/OsmAnd-iOS/issues/1272
before/after

draw waypoints icons above gpx track line

---

Resources/en.lproj/Localizable.strings
Sources/AppHost/OAAppDelegate.mm
Sources/AppHost/OsmAndAppImpl.mm
Sources/CarPlay/OACarPlayMapViewController.mm
Sources/Controllers/2.0/Settings/OAGlobalSettingsViewController.h
Sources/Controllers/2.0/Settings/OAGlobalSettingsViewController.m
Sources/Helpers/OAAppSettings.h
Sources/Helpers/OAAppSettings.m

https://github.com/osmandapp/OsmAnd-Issues/issues/483
video:
https://www.dropbox.com/s/oxe3l19r714eeoa/Screen%20Recording%202021-06-19%20at%2010.09.21.mov?dl=0

add select carplay mode menu

---

Resources/en.lproj/Localizable.strings
Sources/Controllers/2.0/Settings/OAGlobalSettingsViewController.h
Sources/Controllers/2.0/Settings/OAGlobalSettingsViewController.m
Sources/Controllers/Panels/OAMapPanelViewController.mm
Sources/Helpers/OAAppSettings.h
Sources/Helpers/OAAppSettings.m

https://github.com/osmandapp/OsmAnd-Issues/issues/640
video:
https://www.dropbox.com/s/ngd74036q4ds53e/Screen%20Recording%202021-06-22%20at%2020.49.54.mov?dl=0

add last used profile menu

---

Sources/Controllers/Map/Layers/OAGPXLayer.mm

https://github.com/osmandapp/OsmAnd-iOS/issues/1272

show small wpt icon above track line

---

Sources/Controllers/2.0/OADirectionsCardController.mm

https://github.com/osmandapp/OsmAnd-iOS/issues/1276

Fix markers direction icons

---

Resources/Controllers/Cells/OACustomSelectionButtonCell.xib
Resources/Controllers/Cells/OACustomSelectionCollapsableCell.xib
Sources/Controllers/2.0/Settings/ImportExport/OAExportItemsSelectionViewController.mm
Sources/Controllers/2.0/Settings/ImportExport/OAImportSettingsViewController.mm
Sources/Controllers/2.0/Settings/OABaseBigTitleSettingsViewController.xib
Sources/Controllers/2.0/Settings/OABaseSettingsWithBottomButtonsViewController.xib
Sources/Controllers/Cells/OACustomSelectionButtonCell.h

https://github.com/osmandapp/OsmAnd-Issues/issues/509
https://user-images.githubusercontent.com/35684515/124471645-ca66a900-dda5-11eb-8f8d-4d4b8b196bd4.mov

UI review fix

---

Sources/Controllers/2.0/RoutePlanning/OARoutePlanningHudViewController.mm
Sources/Controllers/Map/OAMapActions.h
Sources/Controllers/Map/OAMapActions.mm

https://github.com/osmandapp/OsmAnd-iOS/issues/1324
https://www.dropbox.com/s/7ryhwdvuhv6um7t/Screen%20Recording%202021-07-06%20at%2014.42.40.mov?dl=0

Fix navigation profile resetting after attaching to route 2

---

Sources/Controllers/2.0/Settings/OAGlobalSettingsViewController.m

https://github.com/osmandapp/OsmAnd-Issues/issues/483

CarPlay profile menu UI review fix

---

Sources/Controllers/2.0/Settings/ImportExport/OAExportItemsViewController.mm
Sources/Controllers/2.0/Settings/OABaseSettingsWithBottomButtonsViewController.xib

https://user-images.githubusercontent.com/35684515/124900116-71875280-dfe9-11eb-9720-f0801502f917.mov

export screen navbar fix

---

Sources/Controllers/2.0/RoutePlanning/OAOpenAddTrackViewController.mm

oaFoldersCell crash
https://github.com/osmandapp/OsmAnd-Issues/issues/713

don't reuse OAFoldersCell

---

Sources/Models/OAFavoriteItem.mm
Sources/OAFavoritesSettingsItem.mm

https://github.com/osmandapp/OsmAnd-iOS/issues/1309

parking point time import/export fix

---

Sources/Controllers/2.0/Settings/OAOsmAccountSettingsViewController.m

https://github.com/osmandapp/OsmAnd-iOS/issues/1414

hide text in password field

---

Sources/Controllers/2.0/BottomSheet/OABaseBottomSheetViewController.h
Sources/Controllers/2.0/BottomSheet/OABaseBottomSheetViewController.m
Sources/Controllers/2.0/BottomSheet/RouteInfoBottomSheet/OAFollowTrackBottomSheetViewController.mm
Sources/Controllers/2.0/BottomSheet/RoutePlanningBottomSheet/OAPlanningOptionsBottomSheetViewController.mm
Sources/Controllers/2.0/BottomSheet/RoutePlanningBottomSheet/OAPointOptionsBottomSheetViewController.mm
Sources/Controllers/2.0/BottomSheet/RoutePlanningBottomSheet/OASegmentOptionsBottomSheetViewController.mm
Sources/Controllers/2.0/RoutePlanning/InitialRoutePlanningBottomSheetViewController.mm
Sources/Controllers/2.0/RoutePlanning/OAExitRoutePlanningBottomSheetViewController.m
Sources/Controllers/2.0/RoutePlanning/OARoutePlanningHudViewController.h
Sources/Controllers/2.0/RoutePlanning/OARoutePlanningHudViewController.mm
Sources/Controllers/2.0/RoutePlanning/OARoutePlanningHudViewController.xib
Sources/Controllers/2.0/RoutePlanning/OASaveTrackBottomSheetViewController.mm

Task 1:
https://github.com/osmandapp/OsmAnd-iOS/issues/1358
Task 2:
https://github.com/osmandapp/OsmAnd-Issues/issues/230
video:
https://www.dropbox.com/s/7wnacz0nz6r1o0f/Screen%20Recording%202021-07-22%20at%2000.03.12.mov?dl=0

Plane route UI fixes

---

Sources/Controllers/Map/OAMapHudViewController.mm

https://www.dropbox.com/s/g4hvn1mz9kw469k/Screen%20Recording%202021-08-16%20at%2018.30.25.mov?dl=0

fix hud buttons behavior on poi clicked

---

OsmAnd.xcodeproj/project.pbxproj
Sources/Constants/OAColors.h
Sources/Controllers/TargetMenu/OACollapsableNearestPoiTypeView.h
Sources/Controllers/TargetMenu/OACollapsableNearestPoiTypeView.mm
Sources/Controllers/TargetMenu/POI/OAPOIViewController.mm

https://github.com/osmandapp/OsmAnd-iOS/issues/1131
video:
https://www.dropbox.com/s/6zbebnuzorioequ/Screen%20Recording%202021-08-17%20at%2009.57.35.mov?dl=0

Cuisine / Dish POI tags fix

---

Sources/Views/OATargetPointView.h
Sources/Views/OATargetPointView.mm

https://github.com/osmandapp/OsmAnd-iOS/issues/1440
https://www.dropbox.com/s/trv0o6wkf2voncv/Screen%20Recording%202021-08-19%20at%2010.42.16.mov?dl=0

renaming fix

---

Sources/Helpers/OAResourcesUIHelper.mm

https://github.com/osmandapp/OsmAnd-Issues/issues/750
https://www.dropbox.com/s/nmhjuj05stcxqzy/Video%2018.08.2021%2C%2011%2040%2012.mp4?dl=0

fix no newtwork bug. remove wifi alert

---

OsmAnd.xcodeproj/project.pbxproj
Sources/Controllers/Map/OAMapHudViewController.mm
Sources/Controllers/TargetMenu/PointEditing/OAFavoriteEditingHandler.mm

https://github.com/osmandapp/OsmAnd-iOS/issues/1420
https://www.dropbox.com/s/vicxvrnlgn4f5ap/Screen%20Recording%202021-08-20%20at%2010.11.07.mov?dl=0

fix favorite point folder changing

---

Resources/Localizations/en.lproj/Localizable.strings
Sources/CarPlay/OACarPlayDashboardInterfaceController.mm
Sources/Controllers/BottomSheet/RoutePlanningBottomSheet/OAPlanningOptionsBottomSheetViewController.mm
Sources/Controllers/Panels/OAOptionsPanelBlackViewController.m
Sources/Views/OATargetPointView.mm

https://github.com/osmandapp/OsmAnd-Issues/issues/757

renamed Directions to Navigations

---

OsmAnd.xcodeproj/project.pbxproj
Sources/Controllers/TargetMenu/Editors/OAEditTargetViewController.mm
Sources/Controllers/TargetMenu/Favorites/OAFavoriteViewController.h
Sources/Controllers/TargetMenu/Favorites/OAFavoriteViewController.mm
Sources/Controllers/TargetMenu/GPX/OAGPXWptViewController.h
Sources/Controllers/TargetMenu/GPX/OAGPXWptViewController.mm

https://github.com/osmandapp/OsmAnd-iOS/issues/1428

add timestamp row to favorite and wpt point menu

---

Sources/Controllers/Cells/Xibs/OACoodinateSearchCell.xib
Sources/Controllers/TargetMenu/Search/OAQuickSearchCoordinatesViewController.mm

https://github.com/osmandapp/OsmAnd-Issues/issues/102

fix dissappered coordinate input hintbar

---

Sources/Controllers/DashboardOnMap/MapSettings/OAMapSettingsContourLinesScreen.mm
Sources/Controllers/DashboardOnMap/MapSettings/OAMapSettingsTerrainScreen.mm

https://github.com/osmandapp/OsmAnd-iOS/issues/1485
https://www.dropbox.com/s/opljl5k3avlqd7a/Screen%20Recording%202021-09-16%20at%2000.52.33.mov?dl=0

fix downloading indicator crash

---

Sources/Controllers/BottomSheet/OABaseBottomSheetViewController.h
Sources/Controllers/BottomSheet/OABaseBottomSheetViewController.m
Sources/Controllers/BottomSheet/RoutePlanningBottomSheet/OAPlanningOptionsBottomSheetViewController.mm
Sources/Controllers/RoutePlanning/OARoutePlanningHudViewController.mm

https://github.com/osmandapp/OsmAnd-Issues/issues/779
Buttons fixed: Save as new track, Add to track, Route between points.
https://www.dropbox.com/s/0dt187zcxf8kzll/Screen%20Recording%202021-09-16%20at%2013.21.08.mov?dl=0

fix unopened PlaneRoute screens

---

Sources/Controllers/Map/OAMapHudViewController.mm
Sources/Controllers/OABaseScrollableHudViewController.h
Sources/Controllers/OABaseScrollableHudViewController.mm
Sources/Controllers/RoutePlanning/OARoutePlanningHudViewController.h
Sources/Controllers/RoutePlanning/OARoutePlanningHudViewController.mm
Sources/Controllers/RoutePlanning/OARoutePlanningHudViewController.xib

https://github.com/osmandapp/OsmAnd-iOS/issues/1358
Alse now color for this orange button changes before app loaded

Plane route margins fix

---

Sources/Controllers/DashboardOnMap/MapSettings/OAMapSettingsMainScreen.mm
Sources/Controllers/TargetMenu/MapDownload/OAMapDownloadController.mm
Sources/Controllers/TargetMenu/OATargetInfoViewController.mm
Sources/Controllers/TargetMenu/OATargetMenuViewController.h
Sources/Controllers/TargetMenu/OATargetMenuViewController.mm
Sources/Views/OATargetPointView.mm

https://github.com/osmandapp/OsmAnd-Issues/issues/445
video
https://www.dropbox.com/s/rubfvc3ef50bsnx/Screen%20Recording%202021-09-20%20at%2010.21.55.mov?dl=0

Download map context menu fix

---

Resources/Localizations/en.lproj/Localizable.strings
Sources/Controllers/TargetMenu/MapDownload/OAMapDownloadController.mm
Sources/Controllers/TargetMenu/POI/OAPOIViewController.mm

[Task](https://github.com/osmandapp/OsmAnd-iOS/issues/1478)

add ui numbers formatting

---

Sources/Controllers/TargetMenu/MapDownload/OAMapDownloadController.mm
Sources/Controllers/TargetMenu/POI/OAPOIViewController.mm
Sources/Helpers/OAOsmAndFormatter.h
Sources/Helpers/OAOsmAndFormatter.mm

https://github.com/osmandapp/OsmAnd-iOS/issues/1478
also fixed bug with zero map size of downloaded map regions:

fix formatting osm tags with number values

---

Sources/Controllers/DashboardOnMap/MapSettings/OAMapSettingsTerrainScreen.mm

[task](https://github.com/osmandapp/OsmAnd-iOS/issues/1485)
[video](https://www.dropbox.com/s/v8fqsurw048yf9g/Video%2015.10.2021%2C%2010%2007%2007.mp4?dl=0)

fix crash on switching terrain mode while slope map is downloading

---

Sources/Controllers/DashboardOnMap/MapSettings/OAMapSettingsContourLinesScreen.mm
Sources/Controllers/Resources/OAManageResourcesViewController.mm
Sources/Controllers/TargetMenu/MapDownload/OAMapDownloadController.h
Sources/Controllers/TargetMenu/MapDownload/OAMapDownloadController.mm
Sources/Controllers/TargetMenu/OATargetMenuViewController.mm
Sources/Controllers/TargetMenu/POI/OAPOIViewController.mm
Sources/Helpers/OAResourcesUIHelper.h
Sources/Helpers/OAResourcesUIHelper.mm
Sources/Views/OATargetPointView.mm

[Downloads: "Download all" button #562](https://github.com/osmandapp/OsmAnd-Issues/issues/562)
[Crash in Configure Map – Terrain #1485](https://github.com/osmandapp/OsmAnd-iOS/issues/1485)
[Region selection on map + downloaded maps overlay #445](https://github.com/osmandapp/OsmAnd-iOS/issues/1485)
[Update map list similar to Android #885](https://github.com/osmandapp/OsmAnd-Issues/issues/885)
[video](https://www.dropbox.com/s/lwte0hke35g4lzw/Screen%20Recording%202021-11-01%20at%2019.06.47.mov?dl=0)

Download region fix 3

---

Resources/Localizations/en.lproj/Localizable.strings
Sources/Controllers/Cells/OATargetPointViewCell.mm
Sources/Controllers/Map/Layers/OAFavoritesLayer.mm
Sources/Controllers/Map/OADestinationCell.h
Sources/Controllers/Map/OADestinationCell.mm
Sources/Controllers/Panels/OAMapPanelViewController.mm
Sources/Controllers/Settings/ImportExport/SettingsItems/OAFavoritesSettingsItem.mm
Sources/Controllers/TargetMenu/Favorites/OAFavoriteViewController.mm
Sources/Controllers/TargetMenu/Parking/OAParkingViewController.h
Sources/Controllers/TargetMenu/Parking/OAParkingViewController.mm
Sources/Controllers/TargetMenu/PointEditing/OAFavoriteEditingHandler.mm
Sources/GPX/OAGPXDocumentPrimitives.h
Sources/Helpers/OAFavoritesHelper.mm
Sources/Models/OAFavoriteItem.h
Sources/Models/OAFavoriteItem.mm
Sources/QuickAction/Actions/OAFavoriteAction.mm
Sources/Views/OATargetPointView.mm

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/1309)
[video](https://www.dropbox.com/s/j6imtg9m5iusm9f/Screen%20Recording%202021-11-05%20at%2010.07.01.mov?dl=0)

add parking creation time field. import&export it

---

Sources/Controllers/Cells/Xibs/OAIconTitleValueCell.xib
Sources/Controllers/Settings/OATripRecordingSettingsViewController.mm

[issue](https://github.com/osmandapp/OsmAnd-Issues/issues/869)
[video](https://www.dropbox.com/s/bvbfgcyd42w7btp/Video%2008.11.2021%2C%2009%2028%2036.mp4?dl=0)

fix RecordingSettings cell offset

---

Sources/Controllers/Map/Layers/OAMeasurementToolLayer.mm
Sources/Controllers/Panels/OAMapPanelViewController.mm
Sources/Helpers/OAUtilities.m

[issue](https://github.com/osmandapp/OsmAnd-Issues/issues/857)
crash fix: plane route first point creating
(link)
Crash Feedback (Oct 28, 2021 at 7:40 PM)
https://www.dropbox.com/s/7wwvkte7w6ztusi/testflight_feedback-6.zip?dl=0
Crash Feedback (Nov 3, 2021 at 6:06 PM). Crash “Add to a track”
https://www.dropbox.com/s/k8g2d6ykjocf4z0/testflight_feedback-4.zip?dl=0

Crashes fix

---

Sources/Controllers/TargetMenu/Search/OAQuickSearchCoordinatesViewController.mm
Sources/Models/OAPointDescription.mm

[issue](https://github.com/osmandapp/OsmAnd-Issues/issues/102)
[video](https://www.dropbox.com/s/gu88fmk7gnfpxs0/Video%2008.11.2021%2C%208%2029%2007%20PM.mp4?dl=0)

move map to point. save to history

---

Sources/Controllers/TargetMenu/GPX/TrackMenu/OATrackMenuHudViewController.mm

[issue](https://github.com/osmandapp/OsmAnd-Issues/issues/928)
[video 1](https://www.dropbox.com/s/n18avlv7drovo3g/Screen%20Recording%202021-11-17%20at%2011.06.18.mov?dl=0)
[video 2](https://www.dropbox.com/s/4oqvdnwxpi61oue/Screen%20Recording%202021-11-17%20at%2011.11.05.mov?dl=0)

fix bug with gpx export from context menu

---

OsmAnd.xcodeproj/project.pbxproj
Sources/Controllers/TargetMenu/GPX/OAGPXListViewController.mm

[Track sorting in My places #810](https://github.com/osmandapp/OsmAnd-Issues/issues/810)
[video](https://www.dropbox.com/s/klw24ltsizml5a5/Screen%20Recording%202021-11-12%20at%2010.52.48.mov?dl=0)

add sorting for My places -> Tracks menu

---

Sources/Controllers/Resources/OAManageResourcesViewController.mm

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/1544)

fix map resource search bug with regions without maps filtering

---

Sources/Controllers/Resources/OAOsmAndLiveSelectionViewController.mm
Sources/Helpers/OAOsmAndLiveHelper.mm

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/1540)
[video](https://www.dropbox.com/s/arr2u175mn63u4b/Screen%20Recording%202021-11-22%20at%2023.57.26.mov?dl=0)

fix live updates switch auto turning on

---

Sources/Controllers/OsmEditing/OAOsmEditingViewController.mm

[issued](https://github.com/osmandapp/OsmAnd-Issues/issues/848)
[video](https://www.dropbox.com/s/19ju7cwyws0468j/Screen%20Recording%202021-11-22%20at%2021.04.42.mov?dl=0)

fix bug with delete/save keyboard panel in OSMEditing screen

---

Sources/Controllers/Cells/OAIconTitleValueCell.h
Sources/Controllers/Cells/Xibs/OAIconTitleValueCell.xib
Sources/Controllers/Cells/Xibs/OASegmentSliderTableViewCell.xib
Sources/Controllers/Cells/Xibs/OASegmentedControlCell.xib
Sources/Controllers/TargetMenu/GPX/TrackMenu/OATrackMenuAppearanceHudViewController.mm
Sources/Helpers/OAGPXAppearanceCollection.mm
Sources/Helpers/OAOsmAndFormatter.h
Sources/Helpers/OAOsmAndFormatter.mm

[issue](https://github.com/osmandapp/OsmAnd-Issues/issues/793)

split interval section UI fixes

---

Sources/Controllers/TargetMenu/GPX/TrackMenu/OATrackMenuAppearanceHudViewController.mm

split intervals ui fix 2

---

Sources/Controllers/RoutePlanning/OAOpenAddTrackViewController.mm
Sources/GPX/OAGPXDocumentPrimitives.h
Sources/GPX/OAGPXDocumentPrimitives.mm

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/1524)
[video](https://www.dropbox.com/s/kgt2cjamuzgz1y8/Screen%20Recording%202021-11-29%20at%2023.20.00.mov?dl=0)

Change routing mode on follow track launch

---

Sources/Controllers/TargetMenu/GPX/OAGPXListViewController.mm

[issue](https://github.com/osmandapp/OsmAnd-Issues/issues/810)

change gpx tracks sotring to case insensitive mode

---

Resources/Localizations/en.lproj/Localizable.strings

Language name typo

---

Sources/Controllers/History/OAHistoryViewController.xib
Sources/Controllers/Map/OADiscountToolbarViewController.mm
Sources/Controllers/Map/OADiscountToolbarViewController.xib
Sources/Controllers/MyPlaces/MyPlaces.storyboard
Sources/Controllers/QuickAction/OAActionAddCategoryViewController.xib
Sources/Controllers/QuickAction/OAActionAddMapSourceViewController.xib
Sources/Controllers/QuickAction/OAActionAddMapStyleViewController.xib
Sources/Controllers/QuickAction/OAActionAddProfileViewController.xib
Sources/Controllers/QuickAction/OAActionConfigurationViewController.xib
Sources/Controllers/QuickAction/OAAddQuickActionViewController.xib
Sources/Controllers/QuickAction/OAQuickActionListViewController.xib
Sources/Controllers/Resources/OAPluginDetailsViewController.xib
Sources/Controllers/Resources/OAPluginPopupViewController.xib
Sources/Controllers/TargetMenu/Favorites/OAFavoriteViewController.xib
Sources/Controllers/TargetMenu/GPX/OAGPXEditWptViewController.xib
Sources/Controllers/TargetMenu/GPX/OAGPXItemViewController.xib
Sources/Controllers/TargetMenu/GPX/OAGPXWptViewController.xib
Sources/Controllers/TargetMenu/Search/OAPOIFilterViewController.xib
Sources/Controllers/TargetMenu/Search/OAQuickSearchViewController.xib

[issue](https://github.com/osmandapp/OsmAnd-Issues/issues/845)
before
after

Discount banner font fix

---

Sources/Models/OAFavoriteItem.mm
Sources/Models/OAGpxWptItem.mm

[issue](https://github.com/osmandapp/OsmAnd-Issues/issues/887)

increase favorite icons resolution

---

Sources/Controllers/Resources/OAOsmAndLiveSelectionViewController.h
Sources/Controllers/Resources/OAOsmAndLiveSelectionViewController.mm

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/1540)
[video](https://www.dropbox.com/s/zzdx12tmwzllqxe/Screen%20Recording%202021-12-13%20at%2015.47.24.mov?dl=0)

live updates saving fix

---

Sources/Controllers/BottomSheet/RouteInfoBottomSheet/OAAddDestinationBottomSheetViewController.mm

[issue](https://github.com/osmandapp/OsmAnd-Issues/issues/1033)
before
after

fix "Add start/destination point" header margins

---

Resources/Localizations/de.lproj/Localizable.strings

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/1698)

German localisation fix

---

Sources/Controllers/Map/Layers/OADownloadedRegionsLayer.mm

[Issue](https://github.com/osmandapp/OsmAnd-Issues/issues/1075)
[Pull request to Core](https://github.com/osmandapp/OsmAnd-core/pull/296)

Highlight region only if map.obf file is downloaded

---

Sources/Controllers/TargetMenu/Search/OAQuickSearchListItem.mm
Sources/Controllers/TargetMenu/Search/OAQuickSearchTableController.mm
Sources/Helpers/OAFavoritesHelper.h
Sources/Helpers/OAFavoritesHelper.mm
Sources/Models/OAFavoriteItem.mm
Sources/Models/OAGpxWptItem.mm

fix gpx and wpt icons in search

---

Sources/Controllers/QuickAction/OAActionConfigurationViewController.mm
Sources/Helpers/OAFavoritesHelper.mm
Sources/Helpers/OAUtilities.m

---
OASearchCategoriesListController
OAMapSettingsPOIScreen
OAWaypointsPOIScreen
OAActionConfigurationViewController
OAPOIFilterViewController
OAQuickSearchTableController
OARearrangeCustomFiltersViewController
OAFavoritesHelper (getCompositeIcon)
OALocationPointWrapper

MX icons refactoring

---

OsmAnd.xcodeproj/project.pbxproj
Resources/Localizations/en.lproj/Localizable.strings
Sources/Controllers/Settings/OAProfileDataObject.h
Sources/Controllers/Settings/OAProfileDataObject.m
Sources/Helpers/OAAppSettings.m
Sources/OAApplicationMode.h
Sources/OAApplicationMode.m

[issue](https://github.com/osmandapp/OsmAnd-Issues/issues/814)

add horse profile

---

Sources/Controllers/TargetMenu/OAEditPointViewController.mm

[issue](https://github.com/osmandapp/OsmAnd-Issues/issues/936)
[video](https://www.dropbox.com/s/x84npd2vv1mk4ij/Screen%20Recording%202022-02-10%20at%2016.17.15.mov?dl=0)

favorites icons review fix

---

Sources/Controllers/Panels/OAMapPanelViewController.mm
Sources/Views/OATargetMultiView.h
Sources/Views/OATargetMultiView.mm

[issue](url)
[video before](https://www.dropbox.com/s/i6ehwvygl9aco13/Screen%20Recording%202022-02-10%20at%2018.12.18.mov?dl=0)
[video after](https://www.dropbox.com/s/9vp8r8z2c8nx4vp/Screen%20Recording%202022-02-10%20at%2018.06.47.mov?dl=0)
[video after - v2](https://www.dropbox.com/s/0ezxrj13za5oj77/Screen%20Recording%202022-02-14%20at%2018.14.00.mov?dl=0)

deny intermediate point multiple selection

---

Resources/Localizations/en.lproj/Localizable.strings
Sources/Controllers/BottomSheet/RoutePlanningBottomSheet/OAPointOptionsBottomSheetViewController.mm
Sources/Helpers/OAMapUtils.h
Sources/Helpers/OAMapUtils.mm

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/1753)
[video](https://www.dropbox.com/s/iw4yjf5mf2l2l0b/Screen%20Recording%202022-02-22%20at%2011.03.30.mov?dl=0)

add distance to plan route split at point

---

Sources/Controllers/TargetMenu/OACollapsableTransportStopRoutesView.mm

[issue](https://github.com/osmandapp/OsmAnd-Issues/issues/859)

fix public transport icon size& and separator

---

Sources/Constants/OAAppVersionDependentConstants.h
Sources/Constants/OAAppVersionDependentConstants.m
Sources/Controllers/Map/Layers/OAGPXLayer.mm
Sources/Controllers/Map/OAMapViewController.mm
Sources/GPX/OAGPXDocument.mm
Sources/GPX/OAGPXMutableDocument.mm
Sources/Plugins/Monitoring/OAMonitoringPlugin.mm

[issue](https://github.com/osmandapp/OsmAnd-Issues/issues/1212)

adding app build version to recorded gpx file

---

Sources/CarPlay/OACarPlayDashboardInterfaceController.mm
Sources/Controllers/Panels/OAMapPanelViewController.mm
Sources/Router/OARoutingHelper.h

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/1214)
[video](https://www.dropbox.com/s/djozsv5cip6krqz/Screen%20Recording%202022-03-29%20at%2002.37.56.mov?dl=0)

sync route to carplay

---

Sources/Controllers/Panels/OAMapPanelViewController.mm
Sources/Controllers/RoutePlanning/InitialRoutePlanningBottomSheetViewController.mm
Sources/Controllers/RoutePlanning/OAOpenAddTrackViewController.mm

[issue](https://github.com/osmandapp/OsmAnd-Issues/issues/641)
[video](https://www.dropbox.com/s/grazuhkfopckohs/Screen%20Recording%202022-04-01%20at%2009.48.41.mov?dl=0)

add waypoint menu fix

---

Sources/Controllers/Resources/OAOnlineTilesEditingViewController.mm
Sources/Core/OASQLiteTileSourceMapLayerProvider.mm
Sources/Map/OASQLiteTileSource.h
Sources/Map/OASQLiteTileSource.mm
Sources/Map/OATileSource.mm

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/1838)
[video](https://www.dropbox.com/s/okz5310fjk9cy61/Screen%20Recording%202022-04-07%20at%2010.30.48.mov?dl=0)
[map file for testing](https://www.dropbox.com/s/6bk6m1a1d5xm2n7/maps_with_time.osf?dl=0)

fix online raster maps expire time bugs

---

OsmAnd.xcodeproj/project.pbxproj
Resources/Localizations/en.lproj/Localizable.strings
Sources/AppHost/OsmAndAppImpl.mm
Sources/CarPlay/OACarPlayDashboardInterfaceController.mm
Sources/Controllers/Panels/OAMapPanelViewController.mm
Sources/Controllers/RouteInfoMenu/OARoutePreferencesParameters.h
Sources/Controllers/RouteInfoMenu/OARoutePreferencesParameters.mm
Sources/Controllers/RouteInfoMenu/OARouteSettingsBaseViewController.mm
Sources/Controllers/Settings/NavigationSettings/OASimulationNavigationSettingViewController.h
Sources/Controllers/Settings/NavigationSettings/OASimulationNavigationSettingViewController.mm
Sources/Helpers/OAAppSettings.h
Sources/Helpers/OAAppSettings.m
Sources/Router/OARouteCalculationResult.h
Sources/Router/OARouteCalculationResult.mm
Sources/Router/OARouteProvider.h
Sources/Router/OARouteProvider.mm
Sources/Services/OALocationServices.mm
Sources/Services/OALocationSimulation.h
Sources/Services/OALocationSimulation.mm

[issue](https://github.com/osmandapp/OsmAnd-Issues/issues/1304)
[video](https://www.dropbox.com/s/whou7mexjphlxo5/Screen%20Recording%202022-05-06%20at%2010.21.00.mov?dl=0)

Location simulation updating

---

Sources/Search/OAQuickSearchHelper.mm
Sources/Search/OASearchPhrase.h
Sources/Search/OASearchPhrase.mm
Sources/Search/OASearchSettings.h
Sources/Search/OASearchSettings.mm

search_with_dash_fix

---

Sources/Controllers/Map/Widgets/OARulerWidget.mm

[issue](https://github.com/osmandapp/OsmAnd-Issues/issues/1396)

Sync Radius ruler code with Android

---

Sources/Services/OALocationSimulation.mm

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/2023)
[video](https://www.dropbox.com/s/9rxr2j9haogdimk/Screen%20Recording%202022-06-21%20at%2010.26.43.mov?raw=1)

tune_realistic_speed_simulation

---

Sources/Controllers/TargetMenu/Mapillary/OAMapillaryImageViewController.mm

[video](https://www.dropbox.com/s/xq6ade6e0zddw6t/Screen%20Recording%202022-08-04%20at%2019.01.24.mov?raw=1)

mapillary show indicator on tap

---

Sources/Controllers/Panels/OAMapPanelViewController.mm
Sources/Router/OARouteProvider.mm

[issue](https://github.com/osmandapp/OsmAnd/issues/14801)
Android
https://github.com/osmandapp/OsmAnd/blob/22e40f113ce5c6df97f2f1687d5024ae38a4d28b/OsmAnd/src/net/osmand/plus/views/layers/MapControlsLayer.java#L564

location simulation fixes

---

Sources/Controllers/Map/Layers/OAOverlayMapLayer.mm
Sources/Views/OAMapRendererView.h
Sources/Views/OAMapRendererView.mm

Merge only with request https://github.com/osmandapp/OsmAnd-core/pull/378
From task https://github.com/osmandapp/OsmAnd/issues/14347

Transparency for vector layer (symbols)

---

Sources/Search/OASearchCoreFactory.mm
Sources/Search/OASearchPhrase.h
Sources/Search/OASearchPhrase.mm
Sources/Search/OASearchResult.h
Sources/Search/OASearchResult.mm
Sources/Search/OASearchUICore.h
Sources/Search/OASearchUICore.mm

[issue](https://github.com/osmandapp/OsmAnd/issues/15138)
[this code in android](https://github.com/osmandapp/OsmAnd/blob/5c61cf4c8d3c678f556ad8dba9073bac9c93a6f1/OsmAnd-java/src/main/java/net/osmand/search/core/SearchResult.java#L118)

Milan search fix

---

Sources/Controllers/Map/Layers/OAOverlayMapLayer.mm

To issue https://github.com/osmandapp/OsmAnd-iOS/issues/2208

Fix transparency after overlay layer on/off

---

Sources/Controllers/Map/Layers/OAOverlayMapLayer.mm
Sources/Controllers/Map/OAMapViewController.h
Sources/Controllers/Map/OAMapViewController.mm
Sources/Helpers/OAAppSettings.h
Sources/Helpers/OAAppSettings.m
Sources/Views/OAMapRendererView.h
Sources/Views/OAMapRendererView.mm

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/2208)
[video1](https://www.dropbox.com/s/17e3s3udkli8bar/Screen%20Recording%202022-10-10%20at%2020.55.16.mov?raw=1)
[video2](https://www.dropbox.com/s/1fxdyhya7juwj5j/Screen%20Recording%202022-10-10%20at%2020.57.12.mov?raw=1)
[video3](https://www.dropbox.com/s/vpmwfv018x1e52w/Screen%20Recording%202022-10-10%20at%2021.01.15.mov?raw=1)
[Ardroid PR](https://github.com/osmandapp/OsmAnd/pull/15369/files)

Fix half half transparent map labels

---

Sources/Router/OARouteCalculationResult.h
Sources/Router/OARouteCalculationResult.mm
Sources/Router/OARoutingHelper.mm

Issue https://github.com/osmandapp/OsmAnd-Issues/issues/1597
Android PR https://github.com/osmandapp/OsmAnd/pull/15499

Fix bearing

---

Sources/FirstUsage/OAFirstUsageWizardController.mm

https://user-images.githubusercontent.com/111898301/196979970-f4284abe-41f3-4aec-948e-c5ec0084770e.mp4

Open links internally in the app

---

Sources/Controllers/Settings/OSMEditing/OAOsmEditingSettingsViewController.mm

https://user-images.githubusercontent.com/111898301/197216990-944035cc-14db-4015-ace3-b68bcc4ac74c.mp4

OpenStreetMap OAuth login

---

OsmAnd.xcodeproj/project.pbxproj
Sources/Views/OAMapRendererView.h
Sources/Views/OAMapRendererView.mm
Sources/Views/OATargetPointView.mm
Support Files/OA-Prefix.pch

Share: include coordinates, remove image

---

Sources/Controllers/Map/Widgets/OAFPSTextInfoWidget.mm

[video](https://www.dropbox.com/s/8dae2kd695mklo9/Screen%20Recording%202022-10-26%20at%2018.16.18.mov?raw=1)

fps_widget_fix_2

---

Sources/Backup/LocalBackup/SettingsItems/OAAvoidRoadsSettingsItem.mm
Sources/Backup/LocalBackup/SettingsItems/OAFileSettingsItem.mm
Sources/Backup/LocalBackup/SettingsItems/OAGlobalSettingsItem.mm
Sources/Backup/LocalBackup/SettingsItems/OAMapSourcesSettingsItem.mm
Sources/Backup/LocalBackup/SettingsItems/OAOsmEditsSettingsItem.mm
Sources/Backup/LocalBackup/SettingsItems/OAOsmNotesSettingsItem.mm
Sources/Backup/LocalBackup/SettingsItems/OAPoiUiFilterSettingsItem.mm
Sources/Backup/LocalBackup/SettingsItems/OAProfileSettingsItem.mm
Sources/Backup/LocalBackup/SettingsItems/OAQuickActionsSettingsItem.mm
Sources/Backup/LocalBackup/SettingsItems/OASearchHistorySettingsItem.m
Sources/Backup/LocalBackup/SettingsItems/OASettingsItem.h
Sources/Backup/LocalBackup/SettingsItems/OASettingsItem.mm
Sources/Backup/OABackupHelper.mm
Sources/Backup/OABackupImporter.m
Sources/Helpers/OADownloadsItem.mm
Sources/Helpers/OASuggestedDownloadsItem.m

Fixes fro backup (https://github.com/osmandapp/OsmAnd-Issues/issues/1683)

---

Sources/Controllers/Settings/OSMEditing/OABenefitsOsmContributorsViewController.m
Sources/Controllers/Settings/OSMEditing/OAOsmAccountSettingsViewController.h
Sources/Controllers/Settings/OSMEditing/OAOsmAccountSettingsViewController.m
Sources/Controllers/Settings/OSMEditing/OAOsmEditingSettingsViewController.mm
Sources/Controllers/Settings/OSMEditing/OAOsmLoginMainViewController.m

https://user-images.githubusercontent.com/111898301/199243895-9281bb6e-6739-4514-a2e8-4dd975535361.mp4

OpenStreetMap OAuth login and Fix bug

---

Sources/AppHost/OsmAndAppImpl.mm
Sources/Controllers/Settings/OAGlobalSettingsViewController.m

 Add Last used option

---

Sources/Controllers/Settings/ImportExport/OAPluginInstalledViewController.xib
Sources/Helpers/OAUtilities.m

Plugins-screen-layout-on-iPad-1744

---

Sources/Controllers/Map/Widgets/OATopTextView.mm

Synced this PR from Android: [link](https://github.com/osmandapp/OsmAnd/pull/15690/files)
Issue: [link](https://github.com/osmandapp/OsmAnd/issues/14863)
Before / After

streetname widget fix

---

OsmAnd.xcodeproj/project.pbxproj
Resources/Images.xcassets/AppIcon.appiconset/Contents.json
Resources/Localizations/en.lproj/Localizable.strings
Sources/Controllers/DashboardOnMap/MapSettings/OAMapSettingsMainScreen.mm
Sources/Controllers/Map/Layers/OADownloadedRegionsLayer.mm
Sources/Helpers/OAAppSettings.h
Sources/Helpers/OAAppSettings.m

Add option to disable the green map-downloads overlay

---

Sources/Controllers/RouteInfoMenu/OARoutePreferencesParameters.h
Sources/Controllers/RouteInfoMenu/OARouteSettingsBaseViewController.mm
Sources/Controllers/Settings/NavigationSettings/OARouteParametersViewController.mm

[issue](https://github.com/osmandapp/OsmAnd-Issues/issues/1404)
Car - Fuel efficien way
Bike - Fasterst route
Walk

fix_remove_ped_fastest_route

---

Sources/Controllers/Map/OAMapHudViewController.mm

Map and compass settings buttons UI fix

---

Sources/Controllers/Settings/NavigationSettings/OARouteParameterValuesViewController.mm
Sources/Controllers/Settings/NavigationSettings/OARouteParametersViewController.mm
Sources/Controllers/Settings/OABaseSettingsViewController.m

Goods delivery UI update

---

Sources/OsmEdit/OAEditPOIData.mm

[issue](https://github.com/osmandapp/OsmAnd/issues/13660)

osm_editor_hits_fitching_update

---

Resources/Localizations/en.lproj/Localizable.strings
Sources/Controllers/Map/OAMapViewTrackingUtilities.mm
Sources/Controllers/Settings/GeneralSettings/OAProfileGeneralSettingsParametersViewController.m
Sources/Controllers/Settings/GeneralSettings/OAProfileGeneralSettingsViewController.h
Sources/Controllers/Settings/GeneralSettings/OAProfileGeneralSettingsViewController.m

Changes to the "display position" setting

---

Sources/Controllers/Resources/OAManageResourcesViewController.mm

Maps & Resources: Removed description text

---

Sources/Controllers/OsmEditing/OAAdvancedEditingViewController.mm

https://user-images.githubusercontent.com/111898301/209782836-cb8f973d-5575-46c4-aed0-ef29ac9d8716.mp4

OSM edit suggestions jump on every click Fixed

---

Sources/Core/IOAMapTiledCollectionProvider.mm
Sources/Core/OAMapMarkersCollection.h
Sources/Core/OAMapMarkersCollection.mm
Sources/Core/OAOsmNotesMapLayerProvider.mm

Keep providers in memory during asynchronous data obtain calls

Retain providers during acynchronous calls

---

Sources/Controllers/Panels/OAMapPanelViewController.mm
Sources/Views/OATargetPointView.h
Sources/Views/OATargetPointView.mm

Move pin up when Display Position is set to Bottom - fixed

---

Sources/Controllers/TargetMenu/Favorites/OAAddFavoriteGroupViewController.mm

[issue](https://github.com/osmandapp/OsmAnd-Issues/issues/1788)

fix favourites groups color panel

---

Resources/Localizations/en.lproj/Localizable.strings
Sources/Controllers/RouteInfoMenu/GpxUIHelper.swift
Sources/Controllers/Settings/GeneralSettings/OAProfileGeneralSettingsParametersViewController.m
Sources/Controllers/Settings/GeneralSettings/OAProfileGeneralSettingsViewController.m
Sources/Controllers/TargetMenu/POI/OAPOIViewController.mm
Sources/Helpers/OAAppSettings.h
Sources/Helpers/OAAppSettings.m
Sources/Helpers/OAOsmAndFormatter.mm

Renamed nautical miles and added nautical miles/feet

---

Sources/Controllers/BottomSheet/RouteInfoBottomSheet/OAStatisticsSelectionBottomSheetViewController.mm
Sources/Controllers/Cells/OAIconTextTableViewCell.m
Sources/Controllers/Map/OAMapInfoController.mm
Sources/Controllers/RouteInfoMenu/GpxUIHelper.swift
Sources/Controllers/TargetMenu/GPX/TrackMenu/MenuBuilder/OATrackMenuTabSegments.mm
Sources/Controllers/TargetMenu/OARouteBaseViewController.mm
Sources/Controllers/TargetMenu/Routing/OARouteDetailsGraphViewController.mm
Sources/Controllers/TargetMenu/Routing/OARouteDetailsViewController.mm
Sources/Helpers/OAAppSettings.m
Sources/Router/Colorization/OAColoringType.mm

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/2510)
before/after

fix favorite colors menu & some translations

---

Sources/Controllers/TargetMenu/GPX/OAGPXListViewController.mm

translations fix2

---

Resources/Localizations/en.lproj/Localizable.strings
Sources/Helpers/OAAppSettings.m

[fix for comment](https://github.com/osmandapp/OsmAnd-Issues/issues/966#issuecomment-1417967624)

map languages fix

---

Sources/Controllers/TargetMenu/Favorites/OAFavoriteViewController.mm
Sources/Controllers/TargetMenu/GPX/OAGPXWptViewController.mm
Sources/POI/OAPOI.mm
Sources/POI/OAPOIHelper.h
Sources/POI/OAPOIHelper.mm

[issue](https://github.com/osmandapp/OsmAnd-Issues/issues/1723)
before / after:

fix fav and wpt gpx extentions

---

OsmAnd.xcodeproj/project.pbxproj
Sources/CarPlay/OACarPlayActiveViewController.m
Sources/CarPlay/OACarPlayDashboardInterfaceController.mm
Sources/Constants/OAColors.h
Sources/Controllers/Panels/OAMapPanelViewController.mm
Sources/Controllers/RouteInfoMenu/OARouteInfoView.mm
Support Files/OA-Prefix.pch

Do not hide phone UI elements while connected to CarPaly (https://github.com/osmandapp/OsmAnd-Issues/issues/1817)

---

Sources/Controllers/TargetMenu/Favorites/OAFavoriteViewController.mm
Sources/Controllers/TargetMenu/GPX/OAGPXWptViewController.mm
Sources/POI/OAPOI.mm

[issue](https://github.com/osmandapp/OsmAnd-Issues/issues/1723)

fav custom extensions fix

---

Sources/Controllers/TargetMenu/GPX/TrackMenu/OATrackMenuHeaderView.mm

Renaming the export button

---

Sources/Controllers/Cloud/OAStatusBackupTableViewController.mm

https://user-images.githubusercontent.com/111898301/220136599-cc47a32d-d50a-4a00-b85a-c1330c0f0ebf.mp4

Sync progress count not updating in Local tab, stays at 0% - Fixed

---

Sources/Controllers/Map/Widgets/OAAlarmWidget.mm
Sources/Controllers/Map/Widgets/OADestinationsLineWidget.mm
Sources/Controllers/Map/Widgets/OADownloadMapWidget.mm
Sources/Controllers/Map/Widgets/OALanesControl.mm
Sources/Controllers/Map/Widgets/OARulerWidget.mm
Sources/Controllers/Map/Widgets/OATextInfoWidget.mm
Sources/Controllers/Map/Widgets/OATopTextView.mm

Abbreviated exit number - corrected

---

Sources/Controllers/TargetMenu/POI/OAPOIViewController.mm

[issue](https://github.com/osmandapp/OsmAnd/issues/15500#issuecomment-1420475309)
[synced this android commit](https://github.com/osmandapp/OsmAnd/pull/16252/files)

show shower icon

---

Sources/Controllers/Resources/OADownloadMultipleResourceViewController.mm
Sources/Controllers/Resources/OAOutdatedResourcesViewController.mm
Sources/Helpers/OAResourcesUIHelper.mm

Fixed https://github.com/osmandapp/OsmAnd-iOS/issues/2434 & fixed free maps updates

---

Sources/Controllers/Map/Widgets/OATopTextView.mm

Issue https://github.com/osmandapp/OsmAnd/issues/16434
Old issue https://github.com/osmandapp/OsmAnd/issues/14863
Android PR https://github.com/osmandapp/OsmAnd/pull/16523

Fix remove ref from street name

---

Sources/Controllers/Cloud/OACloudAccountCreateViewController.m
Sources/Controllers/Cloud/OACloudAccountLoginViewController.m

Fixed https://github.com/osmandapp/OsmAnd-Issues/issues/1883 (Client side)

---

Sources/Router/OARoutingHelper.mm

Android PR https://github.com/osmandapp/OsmAnd/pull/16548
Issue https://github.com/osmandapp/OsmAnd/issues/16277

Fix recalculation

---

Resources/Localizations/en.lproj/Localizable.strings
Sources/Controllers/MyPlaces/MyPlaces.storyboard
Sources/Controllers/MyPlaces/OAFavoritesTabBarViewController.m
Sources/Controllers/MyPlaces/OAOsmEditsListViewController.mm
Sources/Controllers/TargetMenu/Favorites/OAFavoriteListViewController.h
Sources/Controllers/TargetMenu/Favorites/OAFavoriteListViewController.mm
Sources/Controllers/TargetMenu/GPX/OAGPXListViewController.mm

Add favorites search

---

Sources/Controllers/OASuperViewController.m
Sources/Controllers/Settings/NavigationSettings/OARecalculateRouteViewController.mm
Sources/Controllers/Settings/NavigationSettings/OARepeatNavigationInstructionsViewController.m
Sources/Controllers/Settings/NavigationSettings/OAVoicePromptsViewController.mm

fix some route parameter screens;

Fix Voice prompts screen

---

Sources/Controllers/Resources/OAManageResourcesViewController.mm

The download icon is shifted to the left - Fixed

---

OsmAnd.xcodeproj/project.pbxproj
Resources/Localizations/en.lproj/Localizable.strings
Sources/AppHost/OAAppDelegate.mm
Sources/Constants/OAAppVersionDependentConstants.h
Sources/Constants/OAAppVersionDependentConstants.m
Sources/Controllers/Cloud/OACloudAccountCreateViewController.m
Sources/Controllers/Help/OAHelpViewController.mm
Sources/Controllers/Map/Layers/OAGPXLayer.mm
Sources/Controllers/Map/Layers/OAPOILayer.mm
Sources/Controllers/Map/OAMapViewController.h
Sources/Controllers/Map/OAMapViewController.mm
Sources/Controllers/Map/OANetworkRouteDrawable.h
Sources/Controllers/Map/OANetworkRouteDrawable.mm
Sources/Controllers/Map/OARouteKey.h
Sources/Controllers/Map/OARouteKey.mm
Sources/Controllers/Panels/OAMapPanelViewController.mm
Sources/Controllers/TargetMenu/GPX/TrackMenu/OABaseTrackMenuHudViewController.mm
Sources/Controllers/TargetMenu/GPX/TrackMenu/OATrackMenuHeaderView.h
Sources/Controllers/TargetMenu/GPX/TrackMenu/OATrackMenuHeaderView.mm
Sources/Controllers/TargetMenu/GPX/TrackMenu/OATrackMenuHudViewController.h
Sources/Controllers/TargetMenu/GPX/TrackMenu/OATrackMenuHudViewController.mm
Sources/Core/OACoreResourcesAmenityIconProvider.mm
Sources/Data/OATargetPoint.h
Sources/GPX/OAGPXDatabase.h
Sources/GPX/OAGPXDatabase.mm
Sources/GPX/OANetworkRouteSelectionTask.h
Sources/GPX/OANetworkRouteSelectionTask.mm
Sources/Helpers/OANativeUtilities.h
Sources/Helpers/OANativeUtilities.mm

Track selection by network https://github.com/osmandapp/OsmAnd-Issues/issues/1884

---

Sources/Controllers/Base/OABaseButtonsViewController.h
Sources/Controllers/Base/OABaseButtonsViewController.xib
Sources/Controllers/Settings/OSMEditing/OAOsmUploadGPXViewConroller.m
Sources/Controllers/Settings/OSMEditing/OAOsmUploadGPXVisibilityViewConroller.m
Sources/Controllers/TargetMenu/GPX/TrackMenu/MenuBuilder/OATrackMenuTabActions.mm
Sources/Controllers/TargetMenu/GPX/TrackMenu/OATrackMenuHudViewController.mm
Sources/Helpers/OANetworkUtilities.m

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/1132)

Uploag gpx to osm review fix

---

Sources/Controllers/TargetMenu/Favorites/OAFavoriteViewController.mm
Sources/Views/OATargetPointView.mm

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/2597)
Screenshots with [map file](https://drive.google.com/file/d/1PmYurkeMgOcEzIAfajLmRLrKhxre2MW4/view?usp=sharing) from issue
---
Screenshot with map downloaded from the app already with address:

tune_fav_point_screen

---

Sources/Controllers/Map/Layers/OAFavoritesLayer.mm

https://user-images.githubusercontent.com/111898301/227907822-576ca7d5-adae-4144-b0b3-ef14fc92022b.mp4

Copy address for Favorite point Fixed

---

Sources/Controllers/Map/OADiscountToolbarViewController.xib
Sources/Helpers/OADiscountHelper.mm

Promo banner fix rtl

---

Sources/Controllers/Map/OAMapActions.mm
Sources/OAApplicationMode.m

Сar profile is set by default fix

---

Sources/Controllers/Cells/Xibs/OAPointDescCell.xib

Distance is cropped

---

Sources/Controllers/Cells/Xibs/OAValueTableViewCell.xib
Sources/Views/XibViews/OATargetPointView.xib
Sources/Weather/OAWeatherHelper.mm
Sources/Weather/OAWeatherWebClient.mm

Fixed https://github.com/osmandapp/OsmAnd-Issues/issues/1971 & https://github.com/osmandapp/OsmAnd-iOS/issues/2724

---

Sources/Controllers/ChoosePlan/Views/OAFeatureCardRow.m
Sources/Controllers/ChoosePlan/Views/OAFeatureCardView.m
Sources/Controllers/ChoosePlan/Views/OAPlanTypeCardRow.mm
Sources/Controllers/Resources/OAPurchasesViewController.mm

Don't flip icons

---

Sources/Controllers/Cells/OAValueTableViewCell.m
Sources/Controllers/Settings/OSMEditing/OAOsmUploadGPXViewConroller.m

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/1132)

osm_track_uploading_fix

---

Sources/Controllers/MyPlaces/MyPlaces.storyboard
Sources/Controllers/MyPlaces/OAFavoritesTabBarViewController.m
Sources/Controllers/MyPlaces/OAOsmEditsListViewController.mm
Sources/Controllers/TargetMenu/Favorites/OAFavoriteListViewController.mm
Sources/Controllers/TargetMenu/GPX/OAGPXListViewController.h
Sources/Controllers/TargetMenu/GPX/OAGPXListViewController.mm

Add Search to Tracks OSM Edits

---

Sources/Controllers/Map/OAMapHudViewController.mm
Sources/Helpers/OAAppSettings.m
Sources/OAApplicationMode.h
Sources/OAApplicationMode.m
Sources/Profiles/Data/OARoutingDataObject.h
Sources/Profiles/Data/OARoutingDataObject.m

Add Train profile

---

Sources/Controllers/Resources/OAManageResourcesViewController.mm
Sources/Controllers/TargetMenu/Resources.storyboard

Add search bar

---

Sources/Controllers/Resources/OAOsmAndLiveSelectionViewController.mm
Sources/Helpers/OAOsmAndLiveHelper.mm

https://github.com/osmandapp/OsmAnd-iOS/issues/2823

translation fix

---

OsmAnd.xcodeproj/project.pbxproj
Resources/Localizations/en.lproj/Localizable.strings
Sources/Controllers/TargetMenu/OATargetInfoViewController.mm
Sources/Controllers/TargetMenu/Wiki/OAWikiWebViewController.h
Sources/Controllers/TargetMenu/Wiki/OAWikiWebViewController.mm
Sources/Helpers/OAWikiArticleHelper.h
Sources/Helpers/OAWikiArticleHelper.mm
Sources/POI/OAPOIHelper.h
Sources/POI/OAPOIHelper.mm

[issue](https://github.com/osmandapp/OsmAnd-Issues/issues/1925)
[video](https://www.dropbox.com/s/a0widsw3ds4gxv1/Screen%20Recording%202023-04-25%20at%2001.23.15.mov?dl=0)
Code in android:
https://github.com/osmandapp/Osmand/blob/bef177c5d7a415b747e377b7ff2cda844bb6c05f/OsmAnd/src/net/osmand/plus/wikipedia/WikipediaWebViewClient.java#L37
https://github.com/osmandapp/Osmand/blob/4e025d0ef6df0b52003b6aa39e6658b0a5dfa4a5/OsmAnd/src/net/osmand/plus/wikipedia/WikiArticleHelper.java#L236
https://github.com/osmandapp/Osmand/blob/4e025d0ef6df0b52003b6aa39e6658b0a5dfa4a5/OsmAnd/src/net/osmand/plus/wikipedia/WikiArticleHelper.java#L105

Update search wiki article task

---

Sources/FirstUsage/OAFirstUsageWizardController.mm
Sources/FirstUsage/OAFirstUsageWizardController.xib

World Overview map not added

---

Sources/CarPlay/CarPlayDirectionsControllers/OACarPlayAddressSearchController.mm
Sources/CarPlay/CarPlayDirectionsControllers/OACarPlayCategoryResultListController.mm
Sources/CarPlay/CarPlayDirectionsControllers/OACarPlayFavoriteResultListController.mm
Sources/CarPlay/CarPlayDirectionsControllers/OACarPlayHistoryListController.mm
Sources/CarPlay/CarPlayDirectionsControllers/OACarPlayMarkersListController.mm
Sources/CarPlay/OABaseCarPlayInterfaceController.h
Sources/CarPlay/OABaseCarPlayInterfaceController.mm

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/2677)
[video](https://www.dropbox.com/s/jx00vm4acpvtdkp/Screen%20Recording%202023-05-02%20at%2012.03.21.mov?dl=0)

fix carplay destination names

---

Sources/GPX/OAGPXMutableDocument.mm

Add time to metadata

---

Sources/Controllers/DashboardOnMap/MapSettings/OAMapSettingsPOIScreen.mm
Sources/Controllers/TargetMenu/Search/OAQuickSearchTableController.h
Sources/Controllers/TargetMenu/Search/OAQuickSearchTableController.mm

Cropped text in Category Fixed

---

Sources/Backup/OABackupInfoGenerationTask.m
Sources/Controllers/Cloud/OACloudBackupViewController.mm

fix cloud screen update after purchase;

Cloud - fix state for "no valid subscription"

---

Sources/Views/OATargetPointView.mm
Sources/Views/XibViews/OATargetPointView.xib

https://github.com/osmandapp/OsmAnd-iOS/issues/2695

target view rtl fix

---

Sources/Controllers/Cells/Xibs/OAValueTableViewCell.xib

https://github.com/osmandapp/OsmAnd-iOS/issues/2771
before/after

cell height fix

---

Sources/Controllers/Map/Widgets/OARulerWidget.mm

Don't cut the ruler by 180 longitude

Fix drawing ruler over longitude 180

---

Sources/Controllers/TargetMenu/OARowInfo.m
Sources/Controllers/TargetMenu/POI/OAPOIViewController.mm
Sources/POI/OAPOI.h

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/2776)
before / after:

fix poi url dublicating

---

Sources/Controllers/Resources/OAOsmAndLiveSelectionViewController.mm

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/2823)
[video](https://github.com/osmandapp/OsmAnd-iOS/assets/35684515/8ca94311-9731-4226-ac05-b1e67f421bda)

live_updates_frequency_fix

---

Sources/Controllers/BottomSheet/RouteInfoBottomSheet/OAAddDestinationBottomSheetViewController.mm

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/2815)
https://github.com/osmandapp/OsmAnd-iOS/assets/35684515/0da87651-6854-4560-adf1-049347bb403b

navigation to address fix

---

Sources/Controllers/RouteInfoMenu/OARouteLineAppearanceHudViewController.mm
Sources/Controllers/TargetMenu/GPX/TrackMenu/OABaseTrackMenuHudViewController.mm
Sources/Controllers/TargetMenu/POI/OAPOIViewController.mm
Sources/Views/OATargetPointView.mm

https://github.com/osmandapp/OsmAnd-iOS/issues/2695

target point buttons fix

---

Resources/Localizations/en.lproj/Localizable.strings

Hazmat category Fix

---

Sources/Controllers/Base/OABaseNavbarViewController.m
Sources/Controllers/Settings/OAConfigureProfileViewController.m

https://github.com/osmandapp/OsmAnd-iOS/assets/111898301/77b8f660-cf96-4d7a-96e7-ef401bad0893

Profile icon is updated

---

Sources/Controllers/QuickAction/OAAddQuickActionViewController.m

Delete Search Button

---

Sources/Controllers/TargetMenu/GPX/OAGPXListViewController.mm
Sources/GPX/OAGPXDatabase.mm

Show track name as it is

---

Sources/Controllers/TargetMenu/GPX/TrackMenu/OATrackMenuHudViewController.mm

https://github.com/osmandapp/OsmAnd-iOS/assets/111898301/fac13842-0c52-455b-b7a9-9364ec54db07

Hiking route details - highlight URL

---

Sources/Controllers/TargetMenu/POI/OAPOIViewController.mm

Add title start date

---

Sources/Controllers/TargetMenu/GPX/TrackMenu/MenuBuilder/OATrackMenuTabOverview.mm
Sources/Controllers/TargetMenu/GPX/TrackMenu/OATrackMenuHudViewController.mm

https://github.com/osmandapp/OsmAnd-iOS/assets/111898301/fc84cb98-e311-40f6-ae14-0ba64e5b0f11

Open link in inner safari tab

---

Sources/Controllers/Map/OAMapInfoController.mm

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/2991)
Before:
After:

widgets rtl fix

---

OsmAnd.xcodeproj/project.pbxproj
Sources/Controllers/Map/Widgets/Widgets/OABearingWidget.h
Sources/Controllers/Map/Widgets/Widgets/OABearingWidget.m
Sources/ThirdPart/Geomagnetism-Swift/Geomagnetism.swift
Sources/ThirdPart/Geomagnetism-Swift/GeomagnetismObjCBridge.swift

[Issue](https://github.com/osmandapp/OsmAnd-iOS/issues/2805)

bearing widget

---

Sources/Controllers/TargetMenu/OATransportStopsBaseController.mm
Sources/Controllers/TargetMenu/Routing/OATransportDetailsTableViewController.mm
Sources/Controllers/TargetMenu/Transport/OATransportRouteController.mm
Sources/Transport/OATransportStopRoute.h
Sources/Transport/OATransportStopRoute.mm

[Issue](https://github.com/osmandapp/OsmAnd/issues/15449)
[Ported this commit](https://github.com/osmandapp/OsmAnd/pull/17529/files#diff-c29a92468fcf1c9ffcfc6176fea44474578dca0eab4f550996502182f0a085cd)
Screenshots of all stops:
Trouble was here

Transport stop index fix

---

Sources/Helpers/OAWikiImageHelper.mm

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/2916)
Before / after:

Wikimedia image cards fix

---

Sources/Controllers/TargetMenu/GPX/TrackMenu/OATrackMenuHudViewController.mm
Sources/Controllers/TargetMenu/OATargetInfoViewController.mm
Sources/Controllers/TargetMenu/Wiki/OAWikiWebViewController.mm
Sources/Helpers/OAWikiArticleHelper.h
Sources/Helpers/OAWikiArticleHelper.mm

Tap on Wikipedia link crash Fixed

---

Sources/Controllers/Map/Layers/OABaseVectorLinesLayer.mm
Sources/Controllers/Map/Layers/OAContextMenuLayer.mm
Sources/Controllers/Map/Layers/OADestinationsLayer.mm
Sources/Controllers/Map/Layers/OAGPXLayer.mm
Sources/Controllers/Map/Layers/OAImpassableRoadsLayer.mm
Sources/Controllers/Map/Layers/OAMapillaryLayer.mm
Sources/Controllers/Map/Layers/OAMeasurementToolLayer.mm
Sources/Controllers/Map/Layers/OAMyPositionLayer.mm
Sources/Controllers/Map/Layers/OAOsmEditsLayer.mm
Sources/Controllers/Map/Layers/OAPreviewRouteLineLayer.mm
Sources/Controllers/Map/Layers/OARouteLayer.mm
Sources/Controllers/Map/Layers/OARoutePointsLayer.mm
Sources/Controllers/Map/Layers/OARulerByTapControlLayer.mm
Sources/Core/IOAMapTiledCollectionProvider.mm

Don't transfer bare Skia shared pointers from core API

Avoid using bare Skia shared pointers

---

Sources/Controllers/Cells/OAPointHeaderTableViewCell.h
Sources/Controllers/Cells/Xibs/OAPointHeaderTableViewCell.xib
Sources/Controllers/TargetMenu/Favorites/OAFavoriteListViewController.mm
Sources/Controllers/TargetMenu/GPX/OAGPXListViewController.mm

Unable to unfold folder in My Places Fixed

---

Sources/Controllers/TargetMenu/Resources.storyboard

Dynamic type issues on Updates screen Fixed

---

Sources/Controllers/Map/OAMapViewController.mm
Sources/Views/OAMapRendererView.h
Sources/Views/OAMapRendererView.mm

Use different sky and fog colors for day and night modes

Fix sky and fog colors

---

Sources/Controllers/ConfigureScreen/Map3dModeButtonVisibilityViewController.swift
Sources/Helpers/OAAppSettings.h
Sources/Helpers/OAAppSettings.m

Remove second line from all tabelcells in the view

---

Sources/Controllers/TargetMenu/POI/OAPOIViewController.mm
Sources/Helpers/OAUtilities.h
Sources/Helpers/OAUtilities.m

Inscription tags are treated as link Fixed

---

Sources/Controllers/TargetMenu/GPX/TrackMenu/OADeleteWaypointsViewController.mm

Hide second section

---

Sources/Controllers/RouteInfoMenu/OARoutePreferencesParameters.mm
Sources/Controllers/RouteInfoMenu/OARouteSettingsViewController.mm

Navigation settings loose icons

---

Sources/Core/OAMapillaryTilesProvider.mm
Sources/Core/OAOsmNotesMapLayerProvider.mm
Sources/Core/OASQLiteTileSourceMapLayerProvider.mm
Sources/Core/OAWebClient.h
Sources/Core/OAWebClient.mm
Sources/Weather/OAWeatherWebClient.h
Sources/Weather/OAWeatherWebClient.mm

Use custom objects with shared pointers for SWIG

Use custom objects with shared pointers for SWIG

---

Sources/Controllers/Base/OABaseNavbarViewController.m

NavBar RTL issue Fixed

---

Sources/Models/OAFavoriteItem.mm

Favorites export part of data is missing Fixed

---

Sources/Controllers/Cloud/OACloudBackupViewController.mm
Sources/Controllers/Resources/OAPurchasesViewController.m

OsmAnd Cloud Main screen RTL Fixed

---

Sources/Controllers/TargetMenu/GPX/OAGPXListViewController.mm

https://github.com/osmandapp/OsmAnd-iOS/assets/111898301/3ce7320a-005b-4186-bcd3-f9d7e34f8f93

Hide Actions group in Edit mode

---

Sources/Controllers/Cloud/OACloudBackupViewController.mm

Use native back action

---

OsmAnd.xcodeproj/project.pbxproj
Resources/Localizations/en.lproj/Localizable.strings
Sources/Controllers/DashboardOnMap/MapSettings/OAMapSettingsTerrainParametersViewController.h
Sources/Controllers/DashboardOnMap/MapSettings/OAMapSettingsTerrainParametersViewController.m
Sources/Controllers/DashboardOnMap/MapSettings/OAMapSettingsTerrainParametersViewController.xib
Sources/Controllers/DashboardOnMap/MapSettings/OAMapSettingsTerrainScreen.mm
Sources/Controllers/Map/OAMapHudViewController.mm
Sources/Controllers/Panels/OAMapPanelViewController.h
Sources/Controllers/Panels/OAMapPanelViewController.mm
Sources/Controllers/Settings/OsmandDevelopment/OAOsmandDevelopmentViewController.mm
Sources/Data/OAAppData.h
Sources/Data/OAAppData.m
Sources/Data/OATargetPoint.h
Sources/Helpers/OAResourcesUIHelper.mm

Add 3 d relief

---

Sources/Router/OARouteImporter.h
Sources/Router/OARouteImporter.mm
Sources/Router/OARouteProvider.mm

To issue https://github.com/osmandapp/OsmAnd/issues/17912
**!! Only after PR https://github.com/osmandapp/OsmAnd-core-legacy/pull/144**

Add left side to routing by gpx

---

Sources/Router/OAWaypointHelper.mm

To issue https://github.com/osmandapp/OsmAnd/issues/17723
Code porting from Java https://github.com/osmandapp/OsmAnd/pull/18090

Avoid series of same types alarms

---

Sources/Controllers/DashboardOnMap/MapSettings/OAMapSettingsTerrainParametersViewController.mm
Sources/Controllers/DashboardOnMap/MapSettings/OAMapSettingsTerrainScreen.mm
Sources/Controllers/Resources/OAManageResourcesViewController.mm

Terrain-maps Review-2

---

Sources/Controllers/Map/OAMapViewController.mm
Sources/Views/OAMapRendererView.mm
Sources/Views/OAMapRendererViewProtocol.h

Support zooming to elevated surface

Support zooming to elevated surface

---

Sources/Views/OAMapRendererView.mm

Remove rendering to texture

---

Sources/Controllers/BottomSheet/OABottomSheetViewController.mm
Sources/Controllers/OARootViewController.m
Sources/Extensions/UINavigationController+keyCommands.m

This fixes keyboard input on iPadOS 15+

Fix keyboard input on iPadOS 15+

---

Sources/Controllers/QuickAction/OAFloatingButtonsHudViewController.mm
Sources/Helpers/OAUtilities.m

https://github.com/osmandapp/OsmAnd-iOS/issues/3175
before / after

fix hud floating buttons

---

Resources/Localizations/en.lproj/Localizable.strings
Sources/Controllers/Settings/OATripRecordingSettingsViewController.mm
Sources/Controllers/Settings/OAWikipediaSettingsViewController.m
Sources/Controllers/Settings/OSMEditing/OAOsmEditingSettingsViewController.mm
Sources/Controllers/Settings/WeatherSettings/OAWeatherSettingsViewController.mm
Sources/Data/OAAppData.h
Sources/Data/OAAppData.m
Sources/Plugins/Wikipedia/OAWikipediaPlugin.h
Sources/Plugins/Wikipedia/OAWikipediaPlugin.mm

https://github.com/osmandapp/OsmAnd-iOS/issues/3187

add reset plugin to default button

---

Sources/Controllers/Settings/OATripRecordingSettingsViewController.mm

https://github.com/osmandapp/OsmAnd-iOS/issues/3187

fix reset trip rec to default

---

Resources/Localizations/en.lproj/Localizable.strings
Sources/Controllers/TargetMenu/Wiki/OAWikiMenuViewController.m

https://github.com/osmandapp/OsmAnd-iOS/issues/2954
https://github.com/osmandapp/OsmAnd-iOS/assets/35684515/7202548d-ab6e-47d2-8422-a48d866eb8f2

add context menu button for wiki poi

---

Sources/AppHost/OsmAndAppImpl.mm
Sources/Controllers/TargetMenu/Favorites/OAFavoriteListViewController.mm

fix color palette on favorite list screen;

fix color palette groups

---

Sources/Controllers/TravelGuides/article/TravelArticleDialogViewController.swift

https://github.com/osmandapp/OsmAnd-Issues/issues/2098

fix_image_blinking

---

Sources/Controllers/TravelGuides/data/TravelObfHelper.swift
Sources/Controllers/TravelGuides/search/TravelSearchHelper.swift

https://github.com/osmandapp/OsmAnd-Issues/issues/2098

increase travel guides search speed

---

Resources/Localizations/en.lproj/Localizable.strings
Sources/Controllers/TravelGuides/article/TravelArticleDialogViewController.swift
Sources/Controllers/TravelGuides/article/TravelGuidesNavigationViewController.swift
Sources/Controllers/TravelGuides/data/TravelObfHelper.swift

https://github.com/osmandapp/OsmAnd-iOS/issues/3186
video without file
https://github.com/osmandapp/OsmAnd-iOS/assets/35684515/c126f585-1888-405e-8a66-ffb331c74c1b
video with file
https://github.com/osmandapp/OsmAnd-iOS/assets/35684515/a854db92-5f48-44bc-a8b8-4a77fc6265b8

travel guides navigation fix

---

Resources/Localizations/en.lproj/Localizable.strings
Sources/Controllers/TravelGuides/data/OATravelLocalDataDbHelper.mm
Sources/Controllers/TravelGuides/data/TravelObfHelper.swift
Sources/Controllers/TravelGuides/explore/TravelExploreViewController.swift

fix_travel_popular_articlesfix_travel_popular_articles

---

Sources/Router/OARouteCalculationParams.h
Sources/Router/OARouteRecalculationHelper.mm
Sources/Router/OATransportRoutingHelper.mm

task
https://github.com/osmandapp/OsmAnd/issues/17530
commits
https://github.com/osmandapp/OsmAnd/pull/18515/files
https://github.com/osmandapp/OsmAnd/pull/18581/files
https://github.com/osmandapp/OsmAnd/pull/18594/files

Public transport code synced

---

Sources/Controllers/Cells/Xibs/OAWaypointCell.xib
Sources/Controllers/DashboardOnMap/Waypoints/OAWaypointsMainScreen.mm

navigation waypoints color fix

---

Sources/Controllers/TargetMenu/Favorites/OAFavoriteImportViewController.mm

https://github.com/osmandapp/OsmAnd-iOS/issues/3269

fav_import_folders_bug

---

Sources/Controllers/Resources/OACustomSourceDetailsViewController.mm
Sources/Controllers/Resources/OACustomSourceDetailsViewController.xib

custom plugin colors fix

---

Sources/Controllers/Cells/OARadiusCellEx.m
Sources/Controllers/Cells/Xibs/OARadiusCellEx.xib

Navigation waypoints color fix 2

---

Sources/Controllers/Resources/OACustomSourceDetailsViewController.xib
Sources/Controllers/Resources/OAManageResourcesViewController.mm
Sources/Helpers/OAUtilities.h
Sources/Helpers/OAUtilities.m

Device theme = light
App theme = dark

custom-plugin-colors-fix-2

---

Sources/Controllers/Others/OAWebViewController.h
Sources/Controllers/Others/OAWebViewController.m

https://github.com/osmandapp/OsmAnd-iOS/pull/3306/commits

Cherry pick help

---

Sources/Controllers/DashboardOnMap/MapSettings/OAMapSettingsTerrainParametersViewController.mm

https://github.com/osmandapp/OsmAnd-iOS/assets/35684515/3c57a294-156a-45ad-9415-4ed0fed70b4d

terrain zoom picker fix

---

Sources/Controllers/Settings/WidgetSettings/WidgetsListViewController.swift

https://github.com/osmandapp/OsmAnd-iOS/issues/3156
[video](https://www.dropbox.com/scl/fi/dbv7jtr9nyxqrpofzd81t/Screen-Recording-2024-01-03-at-17.47.31.mov?rlkey=dbk4tbwarrp6prn4l5et9myvm&dl=0)

allow to move widget pages

---

Sources/Data/Coordinates/OALocationConvert.mm

[this code in android](https://github.com/osmandapp/OsmAnd/blob/841b59a55bf795013b804088f73a1fd840b8a123/OsmAnd-java/src/main/java/net/osmand/LocationConvert.java#L204)
DDD MM.MMM
DDD MM SS.S

coordinates widget fix

---

Sources/Controllers/Settings/OsmandDevelopment/OAOsmandDevelopmentViewController.mm
Sources/Helpers/OAAppSettings.h
Sources/Helpers/OAAppSettings.m
Sources/Router/OARouteProvider.mm

To issue https://github.com/osmandapp/OsmAnd/issues/18815

Developer plugin settings for HH routing

---

Sources/Controllers/DashboardOnMap/MapSettings/MapSettingsGpxViewController.swift
Sources/Controllers/MyPlaces/TracksViewController.swift
Sources/Helpers/OAGPXUIHelper.mm

https://github.com/osmandapp/OsmAnd-Issues/issues/1914#issuecomment-1959430079
https://github.com/osmandapp/OsmAnd-iOS/assets/35684515/9536f2da-b51b-46da-9a57-f004400ffda6
https://github.com/osmandapp/OsmAnd-iOS/assets/35684515/e14d4ed9-979c-491e-be13-36fc6aca5bb2
https://github.com/osmandapp/OsmAnd-iOS/assets/35684515/a00e0a5d-3b55-4ce8-82de-ae2437e208ac

fixed bug with moving files. small ui fixes. add pull to refresh

---

Sources/Controllers/MyPlaces/TracksViewController.swift
Sources/Controllers/Panels/OAMapPanelViewController.mm

https://github.com/osmandapp/OsmAnd-Issues/issues/1914
https://github.com/osmandapp/OsmAnd-iOS/assets/35684515/29a87e2d-70e0-4474-bdb2-c6116fc14cdb

My tracks fixes 2

---

OsmAnd.xcodeproj/project.pbxproj
Sources/Controllers/Map/Layers/OAContextMenuLayer.mm
Sources/Controllers/TargetMenu/OATransportStopsBaseController.h
Sources/Controllers/TargetMenu/OATransportStopsBaseController.mm
Sources/Helpers/OAUtilities.h
Sources/Helpers/OAUtilities.m
Sources/Transport/OATransportStop.h
Sources/Transport/OATransportStopAggregated.h
Sources/Transport/OATransportStopAggregated.m

https://github.com/osmandapp/OsmAnd-iOS/issues/3402

Subway stations fix

---

Sources/Controllers/Map/Layers/OAWeatherRasterLayer.mm

Use proper time gaps for weather forecasts

Fix weather forecasts for days after tomorrow

---

Sources/Controllers/Panels/OAMapPanelViewController.mm
Sources/Helpers/OAGPXUIHelper.mm

[issue](https://github.com/osmandapp/OsmAnd-Issues/issues/1914)
https://github.com/osmandapp/OsmAnd-iOS/assets/35684515/fca7f7c9-bfa2-41f5-b33d-53263cb7f9db

fix new name generator for duplicate gpx button

---

Sources/AppHost/SceneDelegate.mm

https://github.com/osmandapp/OsmAnd/pull/19450
https://github.com/osmandapp/OsmAnd/issues/19422

Sync URL params with OsmAnd Web (mode->profile)

---

Sources/Controllers/Panels/OAMapPanelViewController.mm
Sources/Controllers/TargetMenu/GPX/TrackMenu/OATrackMenuHudViewController.mm

[issue](https://github.com/osmandapp/OsmAnd-Issues/issues/1914)
video before
https://github.com/osmandapp/OsmAnd-iOS/assets/35684515/7fc0d6ee-fe06-4267-8bcd-902452eee19e
video after (part 1)
https://github.com/osmandapp/OsmAnd-iOS/assets/35684515/99287220-c845-4ca4-9324-f6ea04c2c01c
video after (part 2)
https://github.com/osmandapp/OsmAnd-iOS/assets/35684515/939e6cab-1c01-4527-bca6-42778b258f8d

gpx context menu closing fix (restoring navController history)

---

Sources/Search/OASearchCoreFactory.mm

transfer from [Android request](https://github.com/osmandapp/OsmAnd/pull/19340)

Fix search large objects by basemap

---

Sources/Controllers/TravelGuides/data/TravelArticle.swift
Sources/Controllers/TravelGuides/data/TravelObfHelper.swift

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/3542)
video before:
https://github.com/osmandapp/OsmAnd-iOS/assets/35684515/746f058b-f7e1-418f-a01c-0f68ce680da3
video after:
https://github.com/osmandapp/OsmAnd-iOS/assets/35684515/b20276aa-76c0-47b2-a124-925e2e336ea7

fix long opening saved travel article

---

Sources/Views/OAMapRendererView.mm

Allow using scale factor to exaggerate elevation of terrain

Support elevation exaggeration for terrain

---

Sources/Router/OARouteCalculationResult.h
Sources/Router/OARouteCalculationResult.mm
Sources/Router/OARoutingHelper.mm

To issue https://github.com/osmandapp/OsmAnd/issues/19498
Android request:
https://github.com/osmandapp/OsmAnd/pull/19611

Fix location jumping

---

Sources/Helpers/OAWikiArticleHelper.mm
Sources/POI/OAPOIHelper.mm

previous version of pr
https://github.com/osmandapp/OsmAnd-iOS/pull/3638

Travel guides saved article lon opening fix 4.7

---

Sources/Controllers/Panels/OAMapPanelViewController.mm

https://github.com/osmandapp/OsmAnd-iOS/issues/3545#issuecomment-2082575099
before
https://github.com/osmandapp/OsmAnd-iOS/assets/35684515/ec28323d-0216-4352-a99f-b348e82992c8
after
https://github.com/osmandapp/OsmAnd-iOS/assets/35684515/f49dc440-0504-4479-a4fc-f2e609f15b05

extra my places opening fix

---

Sources/Controllers/Map/OAMapHudViewController.h
Sources/Controllers/Map/OAMapHudViewController.mm
Sources/Controllers/Map/Widgets/OAMapWidgetRegistry.h
Sources/Controllers/Map/Widgets/OAMapWidgetRegistry.mm
Sources/Controllers/Map/Widgets/OARulerWidget.mm
Sources/Controllers/Map/Widgets/WidgetInfo/MapWidgetInfo.swift
Sources/Controllers/Map/Widgets/Widgets/RulerDistanceWidget.swift

radius ruler doesn't visible if widget were added to the left panel + sync with android code

---

Sources/Controllers/BottomSheet/RoutePlanningBottomSheet/OAPlanningOptionsBottomSheetViewController.mm
Sources/Controllers/RoutePlanning/Commands/OAClearPointsCommand.mm
Sources/Controllers/RoutePlanning/Commands/OAMeasurementModeCommand.h
Sources/Controllers/RoutePlanning/Commands/OAMeasurementModeCommand.mm
Sources/Controllers/RoutePlanning/Commands/OAReversePointsCommand.mm

[Issue](https://github.com/osmandapp/OsmAnd-iOS/issues/3700)
video before
https://github.com/osmandapp/OsmAnd-iOS/assets/35684515/c1afa6e1-481f-4a2c-8846-ceedd604676e
video after
https://github.com/osmandapp/OsmAnd-iOS/assets/35684515/1fbf01b7-3a8a-48aa-a31a-e3db690228ba

fix plan route options buttons

---

Sources/Views/OAMapRendererView.mm

Use zoom limits when rendering

Apply zoom constraints to renderer

---

Sources/Controllers/Resources/OAManageResourcesViewController.mm

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/3739)

custom plugin doubling maps fix

---

Sources/Controllers/TargetMenu/POI/OAPOIViewController.mm
Sources/Controllers/TargetMenu/Search/OAQuickSearchListItem.mm
Sources/POI/OAPOI.h
Sources/POI/OAPOI.mm
Sources/POI/OAPOIHelper.mm

To issue [Sport tag and multivalued (similar to cuisine)](https://github.com/osmandapp/OsmAnd/issues/8483)
Transfer Android/Java code from PR (multivalued support only):
https://github.com/osmandapp/OsmAnd/pull/19898
https://github.com/osmandapp/OsmAnd/pull/20131

Support multivalued POI (amenities)

---

Resources/Localizations/en.lproj/Localizable.strings
Sources/Controllers/RouteInfoMenu/OARoutePreferencesParameters.mm

https://github.com/osmandapp/OsmAnd-iOS/issues/3761
eu / usa

update hazard eu title

---

Sources/Controllers/Map/Layers/OAOsmEditsLayer.mm
Sources/Core/OACoreResourcesAmenityIconProvider.h
Sources/Core/OACoreResourcesAmenityIconProvider.mm
Sources/Core/OAFavoritesMapLayerProvider.h
Sources/Core/OAFavoritesMapLayerProvider.mm
Sources/Core/OAWaypointsMapLayerProvider.h
Sources/Core/OAWaypointsMapLayerProvider.mm

Avoid concurrency during access to POI symbols cache

Fix crash when accessing POI symbols cache

---

Sources/Controllers/Map/OAMapViewController.mm
Sources/Controllers/Map/OAMapViewTrackingUtilities.h
Sources/Controllers/Map/OAMapViewTrackingUtilities.mm

Use smooth animation for zoom and tilt in 3D mode

Zoom and tilt map simultaneously

---

Sources/Router/OARoutingHelper.mm

Transfer from Android and set missing lastGoodRouteLocation
https://github.com/osmandapp/OsmAnd/commit/6dc49bb00be809581c4d400506b42f3831f3f867
https://github.com/user-attachments/assets/99e7b7ff-be2d-4d43-8cf8-d2cb0c2dd98e

Fix dead loop

---

Resources/Localizations/en.lproj/Localizable.strings
Sources/Controllers/DashboardOnMap/MapSettings/OAMapSettingsWeatherScreen.mm
Sources/Controllers/DashboardOnMap/MapSettings/OAWeatherLayerSettingsViewController.h
Sources/Controllers/DashboardOnMap/MapSettings/OAWeatherLayerSettingsViewController.mm
Sources/Controllers/Map/Layers/OAMapLayers.h
Sources/Controllers/Map/Layers/OAMapLayers.mm
Sources/Controllers/Map/Layers/OAWeatherContourLayer.h
Sources/Controllers/Map/Layers/OAWeatherContourLayer.mm
Sources/Controllers/Map/Layers/OAWeatherRasterLayer.h
Sources/Controllers/Map/Layers/OAWeatherRasterLayer.mm
Sources/Controllers/Map/Toolbars/OAWeatherToolbar.mm
Sources/Controllers/Map/Toolbars/OAWeatherToolbar.xib
Sources/Data/OAWeatherBand.mm
Sources/Helpers/OAOsmAndFormatter.h
Sources/Helpers/OAOsmAndFormatter.mm
Sources/Plugins/Weather/OAWeatherPlugin.h
Sources/Plugins/Weather/OAWeatherPlugin.mm
Sources/Views/OAMapRendererView.h
Sources/Views/OAMapRendererView.mm
Sources/Views/OASegmentedSlider.h
Sources/Views/OASegmentedSlider.mm
Sources/Weather/OAWeatherHelper.h
Sources/Weather/OAWeatherHelper.mm
Sources/Weather/OAWeatherWebClient.h
Sources/Weather/OAWeatherWebClient.mm
Sources/Weather/WeatherLayerSettingsViewController.swift
Sources/Weather/WeatherNavigationBarView/WeatherNavigationBarView.swift
Sources/Weather/WeatherNavigationBarView/WeatherNavigationBarView.xib

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/3779)
before / after
video
https://github.com/user-attachments/assets/30c90e20-b17a-41ae-8251-9b4b1604971d
video 2 - little spinner update
https://github.com/user-attachments/assets/a09b0b15-38ee-4079-b740-dfd488c2c6b9

Weather play button

---

Sources/Controllers/Map/Toolbars/OAWeatherToolbarHandlers.mm
Sources/Data/OAAppData.m

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/3779)
Noticed and fixed bug with weather layers visibility state saving.
video before:
https://github.com/user-attachments/assets/d0f00821-7409-49f3-a0e0-a435daeb052a
video after:
https://github.com/user-attachments/assets/874ecded-ba51-4581-822b-45a667950e33

weatket_layres_state_saving_fix

---

Sources/Data/OAAppData.h
Sources/Data/OAAppData.m
Sources/Data/OAWeatherBand.mm

https://github.com/osmandapp/OsmAnd-iOS/issues/3779

Fix weather wind animation unit

---

OsmAnd.xcodeproj/project.pbxproj
Resources/Images.xcassets/Colors/Slider/Contents.json
Resources/Images.xcassets/Colors/Slider/menuButton.colorset/Contents.json
Resources/Images.xcassets/Colors/Slider/sliderGray.colorset/Contents.json
Resources/Images.xcassets/Colors/Slider/sliderMinimum.colorset/Contents.json
Resources/Images.xcassets/Colors/Slider/tintGray.colorset/Contents.json
Sources/Controllers/Cells/OASegmentSliderTableViewCell.h
Sources/Controllers/DashboardOnMap/MapSettings/OAMapSettingsContourLinesScreen.mm
Sources/Controllers/Map/Toolbars/OAWeatherToolbar.mm
Sources/Controllers/Map/Toolbars/OAWeatherToolbar.xib
Sources/Controllers/RouteInfoMenu/OARouteLineAppearanceHudViewController.mm
Sources/Controllers/Settings/NavigationSettings/OAAngleStraightLineViewController.mm
Sources/Controllers/Settings/NavigationSettings/WidgetParameterViewController.swift
Sources/Controllers/TargetMenu/GPX/TrackMenu/OATrackMenuAppearanceHudViewController.mm
Sources/Views/OASegmentedSlider.h
Sources/Views/OASegmentedSlider.mm
Sources/Views/OAWeatherTimeSegmentedSlider.h
Sources/Views/OAWeatherTimeSegmentedSlider.mm

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/3779#issuecomment-2283478057)
https://github.com/user-attachments/assets/4c6488f5-c875-42e1-a774-981cd340ce02

weather_slider_1_minute_step

---

Sources/Controllers/Map/OAMapHudViewController.mm
Sources/Controllers/Panels/OAMapPanelViewController.mm

Before / after
Video before (+ how to reproduce)
https://github.com/user-attachments/assets/82714796-9793-4b88-b362-12e4d7312a54
Video after
https://github.com/user-attachments/assets/f47b0e47-574c-486e-89fc-c63e7da1644e

App start from carplay layout fix

---

Resources/Localizations/en.lproj/Localizable.strings
Sources/Controllers/Cloud/DeleteAccountViewController.swift
Sources/Controllers/Cloud/OACloudAccountBaseViewController.h
Sources/Controllers/Cloud/OACloudAccountBaseViewController.m
Sources/Controllers/Cloud/OACloudAccountLoginViewController.m

[issue](https://github.com/osmandapp/OsmAnd-Issues/issues/2548)
New error with wrong emails:
Add email to first description line:
Video:
https://github.com/user-attachments/assets/6c7d1d0c-ef8f-4d77-afea-4dbabc0a41f2
https://github.com/user-attachments/assets/770c40af-5c16-4b9f-bea3-341e6df268bf
https://github.com/user-attachments/assets/ca5efc5e-9472-4808-a795-e50345b8aef4
https://github.com/user-attachments/assets/9ec7d7a6-c854-48b8-bbd4-32308d66766c
https://github.com/user-attachments/assets/cd43896a-78f4-4044-a088-d5e9c54812e3

Cloud delete account review fix

---

Sources/POI/OAPOIBaseType.h
Sources/POI/OAPOIType.h
Sources/Search/OASearchCoreFactory.mm

Transfer PR
https://github.com/osmandapp/OsmAnd/pull/20755
To issue https://github.com/osmandapp/web/issues/460
Part of ```public AbstractPoiType getAnyPoiTypeByKey(String name, boolean skipAdditional) ``` and ```private AbstractPoiType findInAdds(List<PoiType> adds, String name)``` need for web only.

Transfer Java code for web search

---

Scripts/add_translations.swift

https://github.com/osmandapp/OsmAnd-Issues/issues/2648

translation_script_whirespaces_fix

---

OsmAnd.xcodeproj/project.pbxproj
Resources/Localizations/en.lproj/Localizable.strings
Sources/Controllers/DashboardOnMap/Waypoints/OAWaypointsMainScreen.h
Sources/Controllers/DashboardOnMap/Waypoints/OAWaypointsMainScreen.mm
Sources/Controllers/DashboardOnMap/Waypoints/OAWaypointsViewController.h
Sources/Controllers/DashboardOnMap/Waypoints/OAWaypointsViewController.mm
Sources/Controllers/Map/Widgets/OATopTextView.mm
Sources/Controllers/Panels/OAMapPanelViewController.h
Sources/Controllers/Panels/OAMapPanelViewController.mm
Sources/Controllers/RouteInfoMenu/OARouteInfoView.mm
Sources/Controllers/RouteInfoMenu/OARoutePreferencesParameters.h
Sources/Controllers/RouteInfoMenu/OARoutePreferencesParameters.mm
Sources/Controllers/RouteInfoMenu/OARouteSettingsBaseViewController.mm

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/3952)
Video before:
https://github.com/user-attachments/assets/678b2992-eba8-4b95-b7be-b259d9aa17f0
Video after:
https://github.com/user-attachments/assets/7605e3bf-cb1a-40d8-8420-e7637ebdaf45

Show along

---

Sources/Router/OARouteProvider.mm

This reverts commit a201754cdd63573d41f9e8b0039db26075517c0a.

Set GpxMultiSegmentsApproximation as default (4.9)

---

Sources/Controllers/TargetMenu/Search/OAQuickSearchListItem.mm
Sources/POI/OAPOI.h
Sources/POI/OAPOIHelper.mm

To issue https://github.com/osmandapp/OsmAnd/issues/2993
Only after !!! https://github.com/osmandapp/OsmAnd-core/pull/787

Implement cities in POI searching

---

Sources/Controllers/Cells/Handlers/IconCollectionHandler.swift
Sources/Controllers/Cells/OAInputTableViewCell.m
Sources/Controllers/Cells/Xibs/OAColorsPaletteCell.xib
Sources/Controllers/Cells/Xibs/OAInputTableViewCell.xib
Sources/Controllers/Settings/OAProfileAppearanceViewController.mm
Sources/Controllers/TargetMenu/GPX/TrackMenu/Appearance/OAColorCollectionViewController.m

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/3553#issuecomment-2399475973)
before / after
before / after
video before
https://github.com/user-attachments/assets/424d3129-a788-40a6-b4ed-c49f3ffaa441
video after
https://github.com/user-attachments/assets/0c486821-d919-4197-b2a6-76fca7f8fe42

Profile appearance fix 2

---

Sources/Helpers/DownloadingCellHelper/DownloadingCellResourceHelper.swift
Sources/Helpers/DownloadingListHelper/DownloadingListHelper.swift
Sources/Helpers/OAResourcesUISwiftHelper.h
Sources/Helpers/OAResourcesUISwiftHelper.mm

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/2222)
https://github.com/user-attachments/assets/9c7f7642-41dc-4054-8986-a991b3ac8c9b

downloadings_list_fix_2

---

Sources/Controllers/Map/Widgets/OADestinationsLineWidget.mm

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/4029)
https://github.com/user-attachments/assets/bad6352e-d6cd-482d-84b3-d4b196e0749f

OADestinationsLineWidget carplay crash fix

---

Sources/Controllers/TargetMenu/OATargetMenuViewController.mm
Sources/FirstUsage/OAFirstUsageWizardController.mm
Sources/Helpers/DownloadingCellHelper/DownloadingCellResourceHelper.swift
Sources/Helpers/OAResourcesUISwiftHelper.h
Sources/Helpers/OAResourcesUISwiftHelper.mm

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/2222)
https://github.com/user-attachments/assets/c6a3c651-e3fd-4028-b682-fbd5d83f45f0
https://github.com/user-attachments/assets/baa9e7d2-5b18-4dbf-b412-75456a073075
https://github.com/user-attachments/assets/e760ea0a-2b01-4239-b1d5-77f5116984bd

add new downloaded bytes formatter to another screens

---

Sources/Controllers/Map/Layers/OARouteLayer.mm

Remove gap in front of navigation route after reroute completed

Fix gap in front of navigation route when reroute

---

Sources/CarPlay/OACarPlayMapViewController.mm

Enable battery saving mode while using CarPlay

Enable battery saving mode in CarPlay

---

OsmAnd.xcodeproj/project.pbxproj
Sources/Controllers/Resources/OACustomSourceDetailsViewController/OACustomSourceDetailsViewController.mm
Sources/Controllers/Resources/OAManageResourcesViewController.mm
Sources/Helpers/DownloadingCellHelper/DownloadingCellBaseHelper.swift
Sources/Helpers/OAResourcesUIHelper.mm
Sources/Helpers/OAResourcesUISwiftHelper.mm
Sources/SwiftExtensions/UIFont+Extension.swift

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/2222#issuecomment-2413212023)
video before:
https://github.com/user-attachments/assets/4a9bf426-4be1-4f87-b348-cba65abb9ac7
video adter:
https://github.com/user-attachments/assets/62ebca09-14d7-46fb-ab47-e448cf0620e1

Download list. Monospaced font. Custom resources

---

Sources/Backup/LocalBackup/SettingsItems/OAProfileSettingsItem.mm

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/4016)

voice_provider_export_fix

---

Sources/Controllers/DashboardOnMap/MapSettings/OAMapSettingsLanguageScreen.mm
Sources/Controllers/DashboardOnMap/MapSettings/OAMapSettingsMainScreen.mm
Sources/Controllers/DashboardOnMap/MapSettings/OAMapSettingsPreferredLanguageScreen.mm
Sources/Helpers/OAFileNameTranslationHelper.m
Sources/Helpers/OAUtilities.h
Sources/Helpers/OAUtilities.m

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/4016)
Fixed a little translation bug. Before / after.

Fix translation (Hungarian-formal)

---

Resources/Localizations/en.lproj/Localizable.strings
Sources/Voice/OATTSCommandPlayerImpl.mm

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/4016)

Added error alert on launching Persian tts without downloaded Persian voice file

---

Sources/Controllers/Map/OAMapViewTrackingUtilities.mm
Sources/Helpers/Extensions/CLLocation+Extension.h
Sources/Helpers/Extensions/CLLocation+Extension.m
Sources/Services/OALocationServices.mm
Sources/Services/OALocationSimulation.h
Sources/Services/OALocationSimulation.mm

[issue](https://github.com/osmandapp/OsmAnd-Issues/issues/2746)
synced code with: LocationSimulationThread.java run()
video 1 - track from Plan Route
https://github.com/user-attachments/assets/350145c8-89a4-4086-b7ac-3481b5db5d64
video 2 - track from isuue
https://github.com/user-attachments/assets/163d65b0-dc82-465c-b0b3-369a37f269d9

simulation location crash fix

---

Sources/Router/OARouteProvider.mm

https://github.com/user-attachments/assets/41b26c6a-afc2-41bf-9c14-b3d862ac55c8

gpx_reading_from_lib_fix

---

Sources/Data/OAAppData.m

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/3965)

fix wrong minzoom value after appcrash

---

Sources/Controllers/MyPlaces/TracksViewController.swift
Sources/Controllers/Panels/OAMapPanelViewController.mm
Sources/Controllers/TargetMenu/Search/OAQuickSearchListItem.h
Sources/Controllers/TargetMenu/Search/OAQuickSearchListItem.mm
Sources/Controllers/TargetMenu/Search/OAQuickSearchTableController.mm
Sources/Helpers/OAGPXUIHelper.h
Sources/Helpers/OAGPXUIHelper.mm
Sources/Search/OAObjectType.m

Crash is search after taping on search result + add new ui for gpx cell

---

OsmAnd.xcodeproj/project.pbxproj
Sources/Controllers/Map/Layers/OAPOILayer.mm
Sources/Controllers/TargetMenu/POI/OAPOIViewController.mm
Sources/Map/ObfConstants.swift
Sources/POI/OAPOI.h

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/3955)
before (no osm link)
after (with osm link)
osm links for another poi still correct
for ways too

show osm links for stairs

---

Sources/Controllers/DashboardOnMap/MapSettings/OAMapSettingsMainScreen.mm
Sources/Data/OAMapStyleSettings.h

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/4000)
icon
testing track:
18.853784 98.810255
https://www.openstreetmap.org/way/151464598#map=17/18.854011/98.811228
track in ios:
track in android:

add_dirtbike_icons

---

Sources/Controllers/Map/Widgets/OACurrentStreetName.mm

To issue https://github.com/osmandapp/OsmAnd/issues/21362
Transfer code from https://github.com/osmandapp/OsmAnd/pull/21413

Avoid show ref is shields was created

---

Sources/Controllers/Map/Widgets/OACurrentStreetName.h
Sources/Controllers/Map/Widgets/OACurrentStreetName.mm
Sources/Controllers/Map/Widgets/OATopTextView.mm
Sources/Router/OAExitInfo.h
Sources/Router/OAExitInfo.m
Sources/Router/OARouteCalculationResult.mm
Sources/Router/OARouteDirectionInfo.h
Sources/Router/OARouteDirectionInfo.mm
Sources/Router/OAVoiceRouter.mm

To issue https://github.com/osmandapp/OsmAnd/issues/21362
Transfer PR https://github.com/osmandapp/OsmAnd/pull/21476
Depends from https://github.com/osmandapp/OsmAnd-core-legacy/pull/264 and https://github.com/osmandapp/OsmAnd-core/pull/811

Fix shields and destination

---

Sources/Router/OATransportRoutingHelper.mm

To issue https://github.com/osmandapp/OsmAnd/issues/20784
Transfer Android PR https://github.com/osmandapp/OsmAnd/pull/21538

Fix public transport routing

---

Sources/Controllers/Map/Widgets/Widgets/GlideAverageWidget.swift
Sources/Controllers/Map/Widgets/Widgets/GlideBaseWidget.swift

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/4146)
before/after:

avg_glide_ratio_icon_fix

---

Sources/Controllers/Map/Layers/OAMapLayers.mm
Sources/Controllers/Map/Layers/OAMyPositionLayer.mm
Sources/Controllers/Map/Layers/OAWeatherContourLayer.mm

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/4161)
video - before:
https://github.com/user-attachments/assets/9ff33a72-1d90-428f-be76-45c88c47637b
video - after:
https://github.com/user-attachments/assets/08038660-2b54-403e-a8f4-01dcdb53ec24
video - fix explanation:
https://github.com/user-attachments/assets/cf5fafcc-8b03-4dbf-9f1e-49f838e1f99b

weather_contour_animations_crash_fix

---

Sources/QuickAction/Actions/OANavVoiceAction.m

Voice navigation as a quick action Fix

---

Sources/Plugins/Weather/OAWeatherPlugin.mm

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/4219)
https://github.com/user-attachments/assets/11ad9b4c-e6c8-4ba9-8c45-886cdd581d32

weather_toolbar_fix

---

Sources/Controllers/OsmEditing/OAOsmEditingViewController.mm
Sources/Controllers/Settings/OSMEditing/OAOsmNoteViewController.mm
Sources/Controllers/Settings/OSMEditing/OAOsmUploadPOIViewController.m

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/4088)
before log out
https://github.com/user-attachments/assets/34b93054-6913-47bb-bcf3-4dbe2409caac
before log in - upload poi
https://github.com/user-attachments/assets/90436efb-a6ce-451b-9258-7b9e0891eefc
before log in - delete poi
https://github.com/user-attachments/assets/ba32331b-53fd-4313-8726-735b25a44b24
after log out
https://github.com/user-attachments/assets/a266ed09-d075-42a9-b7f3-6af46e005673
after log in - upload poi
https://github.com/user-attachments/assets/08b11653-1299-47a9-b4ca-e94469ec92f2
after log in - delete poi
https://github.com/user-attachments/assets/d8ffceaa-42ff-404d-86fc-960b4d7e9bf9

Osm edit upload menu 2

---

Sources/Controllers/Map/Layers/OAMeasurementToolLayer.mm
Sources/Controllers/Map/OAMapViewController.mm
Sources/Controllers/RoutePlanning/Commands/OAReversePointsCommand.mm

Fix crash with null wpt

---

Sources/Controllers/TargetMenu/OAEditPointViewController.mm

Open waypoint of track, edit waypoint

Fix crash index of bounds

---

Sources/Controllers/RoutePlanning/OARouteExporter.mm

To issue https://github.com/osmandapp/OsmAnd-iOS/issues/4247

Fix too much memory allocation

---

Sources/Helpers/MissingMapsCalculator/MissingMapsCalculator.mm

Transfer https://github.com/osmandapp/OsmAnd/pull/21679
To issue https://github.com/osmandapp/OsmAnd-iOS/issues/4227

Fix missing maps

---

Resources/Localizations/en.lproj/Localizable.strings
Sources/Controllers/Map/Widgets/Helpers/OAAverageSpeedComputer.h
Sources/Controllers/Map/Widgets/Helpers/OAAverageSpeedComputer.m
Sources/Controllers/Map/Widgets/OABaseWidgetView.h
Sources/Controllers/Map/Widgets/OABaseWidgetView.m
Sources/Controllers/Map/Widgets/OATextInfoWidget.h
Sources/Controllers/Map/Widgets/TextInfoWidget+Extension.swift
Sources/Controllers/Map/Widgets/WidgetInfo/MapWidgetInfo.swift
Sources/Controllers/Map/Widgets/Widgets/AverageSpeedWidget.swift
Sources/Controllers/Settings/WidgetSettings/WidgetConfigurationViewController.swift

https://github.com/osmandapp/OsmAnd-iOS/issues/4166

Add Reset avg speed as action #4166

---

Sources/Controllers/Map/Layers/OAMyPositionLayer.mm
Sources/Controllers/Map/OAMapHudViewController.mm

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/4197)
video - before:
https://github.com/user-attachments/assets/694081d3-570a-4568-9da9-fbcb20d86718
video - broken because of this [request](https://github.com/osmandapp/OsmAnd-iOS/pull/4039) 
https://github.com/user-attachments/assets/b6372cc8-0ad2-41b3-ac22-9f324c462b2d
video - fixed white icon bug
https://github.com/user-attachments/assets/a6fa1118-b684-4355-8e4a-2cee52c6d68a
video - fixed non updating color bug
https://github.com/user-attachments/assets/8dc08b91-9a68-47a4-a5d8-3d8e7b67db19

my_position_color_fix

---

Resources/Localizations/en.lproj/Localizable.strings
Sources/Controllers/MyPlaces/TracksSortModeHelper.swift
Sources/Controllers/TargetMenu/GPX/TrackMenu/MenuBuilder/OATrackMenuTabSegments.mm
Sources/Helpers/SharedLibHelpers/GpxDataItemExtension.swift

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/3956)
[android pr](https://github.com/osmandapp/OsmAnd/pull/21700)
video after
https://github.com/user-attachments/assets/493bd1e8-a23e-456d-8a97-bc3400c09b5d
https://github.com/user-attachments/assets/ba301994-c493-43b6-8b96-cb355e61e049

use Expected_durationd field from db

---

Scripts/add_translations.swift

before - deprecation code warnings
after - no warnings

traslation_script_deprecated_update

---

Resources/Localizations/en.lproj/Localizable.strings
Sources/Controllers/MyPlaces/TracksSortModeHelper.swift
Sources/Controllers/TargetMenu/GPX/TrackMenu/MenuBuilder/OATrackMenuTabSegments.mm
Sources/Helpers/OAAppSettings.m
Sources/Helpers/SharedLibHelpers/GpxDataItemExtension.swift

https://github.com/osmandapp/OsmAnd-iOS/pull/4279
https://github.com/osmandapp/OsmAnd-iOS/pull/4287

cherry-pick pr from master to 4.9

---

Sources/Backup/LocalBackup/OASettingsHelper.mm
Sources/Backup/LocalBackup/SettingsItems/OAHistoryMarkersSettingsItem.mm
Sources/Backup/LocalBackup/SettingsItems/OAMarkersSettingsItem.mm
Sources/Backup/LocalBackup/SettingsItems/OAProfileSettingsItem.mm
Sources/Backup/LocalBackup/SettingsItems/OASearchHistorySettingsItem.m
Sources/Backup/LocalBackup/SettingsItems/OASettingsItem.mm
Sources/Constants/OAIndexConstants.h
Sources/Controllers/Cloud/OAStatusBackupTableViewController.mm
Sources/Data/OAMapSource.m
Sources/History/OAHistoryDB.h
Sources/History/OAHistoryDB.mm
Sources/History/OAHistoryHelper.h
Sources/History/OAHistoryHelper.m
Sources/OAApplicationMode.m

Needs to be cherry-picked to 4.9 first

1. Add proper sorting 2. Add proper clases!

---

Sources/Controllers/TargetMenu/OATargetInfoViewController.mm

https://github.com/user-attachments/assets/c37d76f1-9cb8-4f60-8c92-308374206061

zoom 4 polygons crash fix

---

Sources/Backup/LocalBackup/ImportExportData/OAExportSettingsType.h
Sources/Backup/LocalBackup/ImportExportData/OAExportSettingsType.mm
Sources/Controllers/Cloud/OAStatusBackupTableViewController.mm
Sources/Helpers/DownloadingCellHelper/DownloadingCellBaseHelper.swift
Sources/Helpers/DownloadingCellHelper/DownloadingCellCloudHelper.swift
Sources/Helpers/DownloadingCellHelper/DownloadingCellResourceHelper.swift

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/4155)
video:
https://github.com/user-attachments/assets/9c075f41-2bef-4d4d-b6b3-4e31eaf573a9

Download cell fixes

---

OsmAnd.xcodeproj/project.pbxproj
Sources/Common/OACollatorStringMatcher.m
Sources/Helpers/OAArabicNormalizer.h
Sources/Helpers/OAArabicNormalizer.mm
Sources/Search/OASearchCoreFactory.mm

To issue https://github.com/osmandapp/OsmAnd/issues/11709

Arabic normalizer

---

Sources/Controllers/TargetMenu/OATargetInfoViewController.mm
Sources/POI/RenderedObjectHelper.swift

[issue](https://github.com/osmandapp/OsmAnd-Issues/issues/2734#issuecomment-2631412220)
before
after

Poi polygon name finding fix

---

Sources/Controllers/BottomSheet/PublicTransportOptionsBottomSheet/OAPublicTransportOptionsBottomSheet.mm
Sources/Controllers/Cells/OATargetPointViewCell.mm
Sources/Controllers/DashboardOnMap/MapSettings/OAMapSettingsPOIScreen.mm
Sources/Controllers/DashboardOnMap/Waypoints/OAWaypointsPOIScreen.mm
Sources/Controllers/OsmEditing/OAPoiTypeSelectionViewController.mm
Sources/Controllers/TargetMenu/Search/OAQuickSearchTableController.mm
Sources/Helpers/OAUtilities.m
Sources/History/OAHistoryItem.m

[issue](https://github.com/osmandapp/OsmAnd-Issues/issues/2734)
before
https://github.com/user-attachments/assets/aac073d4-f09a-429c-8f53-54ebfd2c488d
after
https://github.com/user-attachments/assets/ff66a2e5-c6b6-492b-b9c3-3a83c610b0bd

orange_icons_fix_2

---

Sources/Controllers/Map/Layers/OAMyPositionLayer.mm
Sources/Helpers/OANativeUtilities.h
Sources/Helpers/OANativeUtilities.mm

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/4337)
video:
https://github.com/user-attachments/assets/c51bd4b5-5479-4aca-a038-fadc8676e10f

use profile color for location radius

---

Sources/Controllers/OARootViewController.m

https://github.com/osmandapp/OsmAnd/discussions/21888#discussioncomment-12186875

Added 'L' key for Recenter map action

---

Sources/OsmEdit/OAOpenStreetMapRemoteUtil.mm

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/4418)
video 1 - no crash for [task poi](https://www.openstreetmap.org/way/348624136)
https://github.com/user-attachments/assets/854ed9bd-0322-4452-a1cf-0e23e1528ad3
video 2 - edit and upload to osm [another polygon](https://www.openstreetmap.org/way/1086019412)
https://github.com/user-attachments/assets/e95f3267-432d-48ce-89ce-2cb24634cf73

fix_polygon_osm_edit_crash

---

Sources/Controllers/Map/OAMapActions.mm

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/4296)
video before:
https://github.com/user-attachments/assets/31e77e53-3a38-4c83-87c3-1a255dd772ae
---
video after:
https://github.com/user-attachments/assets/b4c8b671-b5a3-4511-9710-427f8370f106
https://github.com/user-attachments/assets/3eb756fe-5ae5-4d7e-b6e9-e6685cc07957

roundabout_fix

---

Sources/Helpers/OAArabicNormalizer.mm
Sources/Search/OASearchResult.mm

PR https://github.com/osmandapp/OsmAnd/pull/22288
PR https://github.com/osmandapp/OsmAnd/pull/22299
To issue https://github.com/osmandapp/OsmAnd/issues/11709

ArabicNormalizer expand

---

Sources/Controllers/Cells/Handlers/IconCollectionHandler.swift
Sources/Controllers/Cells/Handlers/OAColorCollectionHandler.m
Sources/Controllers/Cells/Handlers/PoiIconCollectionHandler.swift

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/3942#issuecomment-2782751569)
https://github.com/user-attachments/assets/70748c92-0168-4e56-bd56-cd3df88aa3fd

Poi component freezing fix

---

Sources/Controllers/Cells/Handlers/OAColorCollectionHandler.m
Sources/Controllers/ItemsCollections/ItemsCollectionViewController.swift
Sources/Controllers/TargetMenu/Favorites/OASelectFavoriteGroupViewController.mm
Sources/Controllers/TargetMenu/OAEditPointViewController.mm
Sources/Controllers/TargetMenu/PointEditing/OABaseEditorViewController.mm

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/4517)
[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/3942)
https://github.com/user-attachments/assets/9b1a293a-b6d4-48a9-b134-aea7c4431107

Color component crashfix

---

Sources/CarPlay/CarPlayDirectionsControllers/OASearchCategoriesListController.mm
Sources/Controllers/DashboardOnMap/MapSettings/OAMapSettingsMainScreen.mm
Sources/Controllers/DashboardOnMap/MapSettings/OAMapSettingsPOIScreen.mm
Sources/Data/OAMapStyleSettings.h
Sources/POI/OAPOIBaseType.mm
Sources/POI/OAPOIParser.m
Sources/POI/OAPOIUIFilter.h

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/4382)
[pr resources](https://github.com/osmandapp/OsmAnd-resources/pull/1210)
Climbing proutes - before / after / android:
---
Water, Nearest Poi - before / after / android:
---
Water, Nearest Poi - before / after / android:
---
before / after

fix_climbing_and_water_icons

---

Sources/Controllers/Cells/Handlers/OABaseCollectionHandler.h
Sources/Controllers/Cells/Handlers/OABaseCollectionHandler.m
Sources/Controllers/Cells/Handlers/OAColorCollectionHandler.m
Sources/Controllers/Cells/Handlers/PoiIconCollectionHandler.swift
Sources/Controllers/DashboardOnMap/MapSettings/OAMapSettingsTerrainParametersViewController.mm
Sources/Controllers/ItemsCollections/ItemsCollectionViewController.swift
Sources/Controllers/MyPlaces/TracksChangeAppearanceViewController.swift
Sources/Controllers/RouteInfoMenu/OARouteLineAppearanceHudViewController.mm
Sources/Controllers/Settings/OAProfileAppearanceViewController.mm
Sources/Controllers/TargetMenu/GPX/TrackMenu/OATrackMenuAppearanceHudViewController.mm
Sources/Controllers/TargetMenu/OAEditPointViewController.mm
Sources/Controllers/TargetMenu/PointEditing/OABaseEditorViewController.mm

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/4517)
before:
https://github.com/user-attachments/assets/4432ba45-0dd2-4501-8740-6421d1f0186d
---
after:
https://github.com/user-attachments/assets/2146c83b-566a-4f06-9ff2-079786662e7e
https://github.com/user-attachments/assets/39f19e16-edc4-4f38-9ab2-58b415bbf67c
https://github.com/user-attachments/assets/83ab7c40-cd32-404d-b632-e8c3993ee40f

Color component - some UI fixes

---

Sources/Search/OASearchUICore.mm

Transfer code
https://github.com/osmandapp/OsmAnd/pull/22426
To issue https://github.com/osmandapp/OsmAnd/issues/21993

Fix deduplication

---

Sources/POI/OAPOICategory.m

To issue https://github.com/osmandapp/OsmAnd-Issues/issues/2966

[5.0] Fix nullSet for search filters

---

Sources/Controllers/Cells/Handlers/OAColorCollectionHandler.m
Sources/Controllers/TargetMenu/GPX/TrackMenu/OATrackMenuAppearanceHudViewController.mm

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/4517#issuecomment-2830467276)
video:
https://github.com/user-attachments/assets/e06a93bb-d9dd-42be-871e-466587e092a6
https://github.com/user-attachments/assets/618ff9db-220e-4006-a6f6-05f806eaf68e

track_appearance_duplicate_color_fix

---

Sources/Controllers/RoutePlanning/Commands/OAChangeRouteModeCommand.mm
Sources/Controllers/RoutePlanning/OAMeasurementEditingContext.mm
Sources/OAApplicationMode.m

There was previous [pull request](https://github.com/osmandapp/OsmAnd-iOS/pull/4538) of this task. But RZR also [fixed](https://github.com/osmandapp/OsmAnd-iOS/pull/4549/files) this bug in another pr. So here is a new branch with his an mine fixes.
---
video before:
https://github.com/user-attachments/assets/096937c1-0828-46b6-8559-7e2cfb8860db
---
video after rzr fix:
https://github.com/user-attachments/assets/37b52618-82cf-4cec-bb11-27f2f6123424
https://github.com/user-attachments/assets/6db81b63-c4f7-4e43-88f1-6041fb2d870c
---
video after v2:
- synced some plan route code
- fixed bug with resetting second segment routing mode to Straight line
https://github.com/user-attachments/assets/a24477d8-f27c-48cd-ad46-12b93dde24e2

Plan route segment fix 2

---

Sources/Controllers/Cells/Handlers/OAColorCollectionHandler.m
Sources/Controllers/MyPlaces/TracksChangeAppearanceViewController.swift

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/3687#issuecomment-2833444373)
fix updating on duplicate/delete:
https://github.com/user-attachments/assets/47698b6a-f6f2-459a-91f3-0e95f7b95fcb
fix animation glitche on screen opening:
https://github.com/user-attachments/assets/d405b697-0e2a-4e50-871c-012a73f109ce

Track folder appearance color bugfix

---

Sources/Controllers/Cells/Handlers/PoiIconCollectionHandler.swift
Sources/Controllers/Cells/OACollectionSingleLineTableViewCell.h
Sources/Controllers/Cells/OACollectionSingleLineTableViewCell.m
Sources/Controllers/Cells/Xibs/OACollectionSingleLineTableViewCell.xib
Sources/Controllers/TargetMenu/OAEditPointViewController.mm
Sources/Controllers/TargetMenu/PointEditing/OABaseEditorViewController.mm

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/3942#issuecomment-2834584702)
Fixed wrong icon detection
https://github.com/user-attachments/assets/8ed0325a-ad46-4368-b63c-7819dc1b581d
---
fixed empty icons in Last used:
---
fixed paddings:

Poi compointent fix 28 04 25

---

Sources/Controllers/ItemsCollections/ItemsCollectionViewController.swift
Sources/Controllers/MyPlaces/TracksChangeAppearanceViewController.swift

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/3687#issuecomment-2841206611)
https://github.com/user-attachments/assets/88098fc0-73e3-4a03-85ae-1b63fd405ff9

Track group configure appearance fix

---

Sources/Controllers/Cells/Handlers/PoiIconCollectionHandler.swift
Sources/Controllers/Settings/OAProfileAppearanceViewController.mm

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/3942#issuecomment-2839119761)
https://github.com/user-attachments/assets/6aaca5bc-e089-4ca4-918e-df5b94efdf74

use_only_profile_icons_in_profile_appearnce_poi_compoinent

---

Sources/Controllers/RoutePlanning/OARoutePlanningHudViewController.mm

https://github.com/osmandapp/OsmAnd-Issues/issues/1587

Fixed center icon position on plane route screen

---

Sources/Controllers/Cells/Handlers/OAColorCollectionHandler.h
Sources/Controllers/Cells/Handlers/OAColorCollectionHandler.m
Sources/Controllers/DashboardOnMap/MapSettings/OAMapSettingsTerrainParametersViewController.mm
Sources/Controllers/ItemsCollections/ItemsCollectionViewController.swift
Sources/Controllers/MyPlaces/TracksChangeAppearanceViewController.swift
Sources/Controllers/TargetMenu/OAEditPointViewController.mm

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/3687#issuecomment-2841206611)
video before:
https://github.com/user-attachments/assets/9ec22621-cdb1-4f8f-a81c-e46b11c36405
---
video after:
https://github.com/user-attachments/assets/ab5a3059-0a79-474f-ad2b-1a1c0398993f

fix_color_pallete_duplicate_and_delete

---

Sources/Controllers/Cells/Handlers/OAColorCollectionHandler.m
Sources/Controllers/TargetMenu/PointEditing/OABaseEditorViewController.h
Sources/Controllers/TargetMenu/PointEditing/OABaseEditorViewController.mm
Sources/Controllers/TargetMenu/PointEditing/OAFavoriteGroupEditorViewController.mm

[issue](https://github.com/osmandapp/OsmAnd-iOS/issues/3687#issuecomment-2847296517)
https://github.com/user-attachments/assets/8a116b85-f43b-47e2-8194-cb441545450b

color_component_last_index_duplicate_crashfix

---

Sources/Router/OARoutingHelper.h
Sources/Router/OARoutingHelper.mm
Sources/Services/OALocationServices.mm
Sources/Services/OALocationSimulation.mm
Sources/Services/OASimulationProvider.h
Sources/Services/OASimulationProvider.mm

Transfer PR: 
https://github.com/osmandapp/OsmAnd/pull/22826
https://github.com/osmandapp/OsmAnd/pull/22828
https://github.com/osmandapp/OsmAnd/pull/22845
Issue: [Current position jumps during tunnel navigation](https://github.com/osmandapp/OsmAnd/issues/22023)

Fix jumping location after tunnels

---

Sources/Search/OASearchResultMatcher.mm

-[SearchIndexItemAPI addResultIfNotExists:existingResults:resultMatcher:] __NSFastEnumerationMutationHandler

search crash fix

---

Sources/Controllers/Map/Layers/OADestinationsLayer.mm
Sources/Controllers/Map/Layers/OASymbolMapLayer.h

https://github.com/osmandapp/OsmAnd-Issues/issues/1587

Propper text size handling for distance marker

---

Sources/Controllers/Map/Layers/OAFavoritesLayer.mm
Sources/Controllers/Map/Layers/OAPOILayer.mm
Sources/Views/OAMapRendererView.h

Update POI symbols on the screen when ready

Redraw POI symbols separately

---

Sources/POI/OATopIndexFilter.mm

To issue https://github.com/osmandapp/OsmAnd/issues/22855

Case insensitive brand search

---

Sources/Controllers/Map/Helpers/OAMapSelectionHelper.mm

review for https://github.com/osmandapp/OsmAnd-Issues/issues/2917
before/after:
---
todo:
this code should be moved to ui layer as part of next task [Combined context menu ->  Lazy loading of POI data](https://github.com/osmandapp/OsmAnd-iOS/issues/4594#issuecomment-3057646942)

poi_lost_fields_quickfix

---

Sources/Search/OASearchResultMatcher.mm
Sources/Search/OASearchUICore.h
Sources/Search/OASearchUICore.mm

https://github.com/osmandapp/OsmAnd/issues/18668#issuecomment-3329663731

Port SearchUICore.calculateAddressString() from Android

---

Sources/Controllers/Map/Helpers/OAMapSelectionHelper.mm

https://github.com/osmandapp/OsmAnd/issues/22226

Improve temporary workaround for new OSM routes
